<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesParaibaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['cidade' => 'Água Branca', 'estado_id' => 15],
            ['cidade' => 'Aguiar', 'estado_id' => 15],
            ['cidade' => 'Alagoa Grande', 'estado_id' => 15],
            ['cidade' => 'Alagoa Nova', 'estado_id' => 15],
            ['cidade' => 'Alagoinha', 'estado_id' => 15],
            ['cidade' => 'Alcantil', 'estado_id' => 15],
            ['cidade' => 'Algodão de Jandaíra', 'estado_id' => 15],
            ['cidade' => 'Alhandra', 'estado_id' => 15],
            ['cidade' => 'Amparo', 'estado_id' => 15],
            ['cidade' => 'Aparecida', 'estado_id' => 15],
            ['cidade' => 'Araçagi', 'estado_id' => 15],
            ['cidade' => 'Arara', 'estado_id' => 15],
            ['cidade' => 'Araruna', 'estado_id' => 15],
            ['cidade' => 'Areia', 'estado_id' => 15],
            ['cidade' => 'Areia de Baraúnas', 'estado_id' => 15],
            ['cidade' => 'Areial', 'estado_id' => 15],
            ['cidade' => 'Aroeiras', 'estado_id' => 15],
            ['cidade' => 'Assunção', 'estado_id' => 15],
            ['cidade' => 'Baía da Traição', 'estado_id' => 15],
            ['cidade' => 'Bananeiras', 'estado_id' => 15],
            ['cidade' => 'Baraúna', 'estado_id' => 15],
            ['cidade' => 'Barra de Santa Rosa', 'estado_id' => 15],
            ['cidade' => 'Barra de Santana', 'estado_id' => 15],
            ['cidade' => 'Barra de São Miguel', 'estado_id' => 15],
            ['cidade' => 'Bayeux', 'estado_id' => 15],
            ['cidade' => 'Belém', 'estado_id' => 15],
            ['cidade' => 'Belém do Brejo do Cruz', 'estado_id' => 15],
            ['cidade' => 'Bernardino Batista', 'estado_id' => 15],
            ['cidade' => 'Boa Ventura', 'estado_id' => 15],
            ['cidade' => 'Boa Vista', 'estado_id' => 15],
            ['cidade' => 'Bom Jesus', 'estado_id' => 15],
            ['cidade' => 'Bom Sucesso', 'estado_id' => 15],
            ['cidade' => 'Bonito de Santa Fé', 'estado_id' => 15],
            ['cidade' => 'Boqueirão', 'estado_id' => 15],
            ['cidade' => 'Borborema', 'estado_id' => 15],
            ['cidade' => 'Brejo do Cruz', 'estado_id' => 15],
            ['cidade' => 'Brejo dos Santos', 'estado_id' => 15],
            ['cidade' => 'Caaporã', 'estado_id' => 15],
            ['cidade' => 'Cabaceiras', 'estado_id' => 15],
            ['cidade' => 'Cabedelo', 'estado_id' => 15],
            ['cidade' => 'Cachoeira dos Índios', 'estado_id' => 15],
            ['cidade' => 'Cacimba de Areia', 'estado_id' => 15],
            ['cidade' => 'Cacimba de Dentro', 'estado_id' => 15],
            ['cidade' => 'Cacimbas', 'estado_id' => 15],
            ['cidade' => 'Caiçara', 'estado_id' => 15],
            ['cidade' => 'Cajazeiras', 'estado_id' => 15],
            ['cidade' => 'Cajazeirinhas', 'estado_id' => 15],
            ['cidade' => 'Caldas Brandão', 'estado_id' => 15],
            ['cidade' => 'Camalaú', 'estado_id' => 15],
            ['cidade' => 'Campina Grande', 'estado_id' => 15],
            ['cidade' => 'Campo de Santana', 'estado_id' => 15],
            ['cidade' => 'Capim', 'estado_id' => 15],
            ['cidade' => 'Caraúbas', 'estado_id' => 15],
            ['cidade' => 'Carrapateira', 'estado_id' => 15],
            ['cidade' => 'Casserengue', 'estado_id' => 15],
            ['cidade' => 'Catingueira', 'estado_id' => 15],
            ['cidade' => 'Catolé do Rocha', 'estado_id' => 15],
            ['cidade' => 'Caturité', 'estado_id' => 15],
            ['cidade' => 'Conceição', 'estado_id' => 15],
            ['cidade' => 'Condado', 'estado_id' => 15],
            ['cidade' => 'Conde', 'estado_id' => 15],
            ['cidade' => 'Congo', 'estado_id' => 15],
            ['cidade' => 'Coremas', 'estado_id' => 15],
            ['cidade' => 'Coxixola', 'estado_id' => 15],
            ['cidade' => 'Cruz do Espírito Santo', 'estado_id' => 15],
            ['cidade' => 'Cubati', 'estado_id' => 15],
            ['cidade' => 'Cuité', 'estado_id' => 15],
            ['cidade' => 'Cuité de Mamanguape', 'estado_id' => 15],
            ['cidade' => 'Cuitegi', 'estado_id' => 15],
            ['cidade' => 'Curral de Cima', 'estado_id' => 15],
            ['cidade' => 'Curral Velho', 'estado_id' => 15],
            ['cidade' => 'Damião', 'estado_id' => 15],
            ['cidade' => 'Desterro', 'estado_id' => 15],
            ['cidade' => 'Diamante', 'estado_id' => 15],
            ['cidade' => 'Dona Inês', 'estado_id' => 15],
            ['cidade' => 'Duas Estradas', 'estado_id' => 15],
            ['cidade' => 'Emas', 'estado_id' => 15],
            ['cidade' => 'Esperança', 'estado_id' => 15],
            ['cidade' => 'Fagundes', 'estado_id' => 15],
            ['cidade' => 'Frei Martinho', 'estado_id' => 15],
            ['cidade' => 'Gado Bravo', 'estado_id' => 15],
            ['cidade' => 'Guarabira', 'estado_id' => 15],
            ['cidade' => 'Gurinhém', 'estado_id' => 15],
            ['cidade' => 'Gurjão', 'estado_id' => 15],
            ['cidade' => 'Ibiara', 'estado_id' => 15],
            ['cidade' => 'Igaracy', 'estado_id' => 15],
            ['cidade' => 'Imaculada', 'estado_id' => 15],
            ['cidade' => 'Ingá', 'estado_id' => 15],
            ['cidade' => 'Itabaiana', 'estado_id' => 15],
            ['cidade' => 'Itaporanga', 'estado_id' => 15],
            ['cidade' => 'Itapororoca', 'estado_id' => 15],
            ['cidade' => 'Itatuba', 'estado_id' => 15],
            ['cidade' => 'Jacaraú', 'estado_id' => 15],
            ['cidade' => 'Jericó', 'estado_id' => 15],
            ['cidade' => 'João Pessoa', 'estado_id' => 15],
            ['cidade' => 'Juarez Távora', 'estado_id' => 15],
            ['cidade' => 'Juazeirinho', 'estado_id' => 15],
            ['cidade' => 'Junco do Seridó', 'estado_id' => 15],
            ['cidade' => 'Juripiranga', 'estado_id' => 15],
            ['cidade' => 'Juru', 'estado_id' => 15],
            ['cidade' => 'Lagoa', 'estado_id' => 15],
            ['cidade' => 'Lagoa de Dentro', 'estado_id' => 15],
            ['cidade' => 'Lagoa Seca', 'estado_id' => 15],
            ['cidade' => 'Lastro', 'estado_id' => 15],
            ['cidade' => 'Livramento', 'estado_id' => 15],
            ['cidade' => 'Logradouro', 'estado_id' => 15],
            ['cidade' => 'Lucena', 'estado_id' => 15],
            ['cidade' => 'Mãe d`Água', 'estado_id' => 15],
            ['cidade' => 'Malta', 'estado_id' => 15],
            ['cidade' => 'Mamanguape', 'estado_id' => 15],
            ['cidade' => 'Manaíra', 'estado_id' => 15],
            ['cidade' => 'Marcação', 'estado_id' => 15],
            ['cidade' => 'Mari', 'estado_id' => 15],
            ['cidade' => 'Marizópolis', 'estado_id' => 15],
            ['cidade' => 'Massaranduba', 'estado_id' => 15],
            ['cidade' => 'Mataraca', 'estado_id' => 15],
            ['cidade' => 'Matinhas', 'estado_id' => 15],
            ['cidade' => 'Mato Grosso', 'estado_id' => 15],
            ['cidade' => 'Maturéia', 'estado_id' => 15],
            ['cidade' => 'Mogeiro', 'estado_id' => 15],
            ['cidade' => 'Montadas', 'estado_id' => 15],
            ['cidade' => 'Monte Horebe', 'estado_id' => 15],
            ['cidade' => 'Monteiro', 'estado_id' => 15],
            ['cidade' => 'Mulungu', 'estado_id' => 15],
            ['cidade' => 'Natuba', 'estado_id' => 15],
            ['cidade' => 'Nazarezinho', 'estado_id' => 15],
            ['cidade' => 'Nova Floresta', 'estado_id' => 15],
            ['cidade' => 'Nova Olinda', 'estado_id' => 15],
            ['cidade' => 'Nova Palmeira', 'estado_id' => 15],
            ['cidade' => 'Olho d`Água', 'estado_id' => 15],
            ['cidade' => 'Olivedos', 'estado_id' => 15],
            ['cidade' => 'Ouro Velho', 'estado_id' => 15],
            ['cidade' => 'Parari', 'estado_id' => 15],
            ['cidade' => 'Passagem', 'estado_id' => 15],
            ['cidade' => 'Patos', 'estado_id' => 15],
            ['cidade' => 'Paulista', 'estado_id' => 15],
            ['cidade' => 'Pedra Branca', 'estado_id' => 15],
            ['cidade' => 'Pedra Lavrada', 'estado_id' => 15],
            ['cidade' => 'Pedras de Fogo', 'estado_id' => 15],
            ['cidade' => 'Pedro Régis', 'estado_id' => 15],
            ['cidade' => 'Piancó', 'estado_id' => 15],
            ['cidade' => 'Picuí', 'estado_id' => 15],
            ['cidade' => 'Pilar', 'estado_id' => 15],
            ['cidade' => 'Pilões', 'estado_id' => 15],
            ['cidade' => 'Pilõezinhos', 'estado_id' => 15],
            ['cidade' => 'Pirpirituba', 'estado_id' => 15],
            ['cidade' => 'Pitimbu', 'estado_id' => 15],
            ['cidade' => 'Pocinhos', 'estado_id' => 15],
            ['cidade' => 'Poço Dantas', 'estado_id' => 15],
            ['cidade' => 'Poço de José de Moura', 'estado_id' => 15],
            ['cidade' => 'Pombal', 'estado_id' => 15],
            ['cidade' => 'Prata', 'estado_id' => 15],
            ['cidade' => 'Princesa Isabel', 'estado_id' => 15],
            ['cidade' => 'Puxinanã', 'estado_id' => 15],
            ['cidade' => 'Queimadas', 'estado_id' => 15],
            ['cidade' => 'Quixabá', 'estado_id' => 15],
            ['cidade' => 'Remígio', 'estado_id' => 15],
            ['cidade' => 'Riachão', 'estado_id' => 15],
            ['cidade' => 'Riachão do Bacamarte', 'estado_id' => 15],
            ['cidade' => 'Riachão do Poço', 'estado_id' => 15],
            ['cidade' => 'Riacho de Santo Antônio', 'estado_id' => 15],
            ['cidade' => 'Riacho dos Cavalos', 'estado_id' => 15],
            ['cidade' => 'Rio Tinto', 'estado_id' => 15],
            ['cidade' => 'Salgadinho', 'estado_id' => 15],
            ['cidade' => 'Salgado de São Félix', 'estado_id' => 15],
            ['cidade' => 'Santa Cecília', 'estado_id' => 15],
            ['cidade' => 'Santa Cruz', 'estado_id' => 15],
            ['cidade' => 'Santa Helena', 'estado_id' => 15],
            ['cidade' => 'Santa Inês', 'estado_id' => 15],
            ['cidade' => 'Santa Luzia', 'estado_id' => 15],
            ['cidade' => 'Santa Rita', 'estado_id' => 15],
            ['cidade' => 'Santa Teresinha', 'estado_id' => 15],
            ['cidade' => 'Santana de Mangueira', 'estado_id' => 15],
            ['cidade' => 'Santana dos Garrotes', 'estado_id' => 15],
            ['cidade' => 'Santarém', 'estado_id' => 15],
            ['cidade' => 'Santo André', 'estado_id' => 15],
            ['cidade' => 'São Bentinho', 'estado_id' => 15],
            ['cidade' => 'São Bento', 'estado_id' => 15],
            ['cidade' => 'São Domingos de Pombal', 'estado_id' => 15],
            ['cidade' => 'São Domingos do Cariri', 'estado_id' => 15],
            ['cidade' => 'São Francisco', 'estado_id' => 15],
            ['cidade' => 'São João do Cariri', 'estado_id' => 15],
            ['cidade' => 'São João do Rio do Peixe', 'estado_id' => 15],
            ['cidade' => 'São João do Tigre', 'estado_id' => 15],
            ['cidade' => 'São José da Lagoa Tapada', 'estado_id' => 15],
            ['cidade' => 'São José de Caiana', 'estado_id' => 15],
            ['cidade' => 'São José de Espinharas', 'estado_id' => 15],
            ['cidade' => 'São José de Piranhas', 'estado_id' => 15],
            ['cidade' => 'São José de Princesa', 'estado_id' => 15],
            ['cidade' => 'São José do Bonfim', 'estado_id' => 15],
            ['cidade' => 'São José do Brejo do Cruz', 'estado_id' => 15],
            ['cidade' => 'São José do Sabugi', 'estado_id' => 15],
            ['cidade' => 'São José dos Cordeiros', 'estado_id' => 15],
            ['cidade' => 'São José dos Ramos', 'estado_id' => 15],
            ['cidade' => 'São Mamede', 'estado_id' => 15],
            ['cidade' => 'São Miguel de Taipu', 'estado_id' => 15],
            ['cidade' => 'São Sebastião de Lagoa de Roça', 'estado_id' => 15],
            ['cidade' => 'São Sebastião do Umbuzeiro', 'estado_id' => 15],
            ['cidade' => 'Sapé', 'estado_id' => 15],
            ['cidade' => 'Seridó', 'estado_id' => 15],
            ['cidade' => 'Serra Branca', 'estado_id' => 15],
            ['cidade' => 'Serra da Raiz', 'estado_id' => 15],
            ['cidade' => 'Serra Grande', 'estado_id' => 15],
            ['cidade' => 'Serra Redonda', 'estado_id' => 15],
            ['cidade' => 'Serraria', 'estado_id' => 15],
            ['cidade' => 'Sertãozinho', 'estado_id' => 15],
            ['cidade' => 'Sobrado', 'estado_id' => 15],
            ['cidade' => 'Solânea', 'estado_id' => 15],
            ['cidade' => 'Soledade', 'estado_id' => 15],
            ['cidade' => 'Sossêgo', 'estado_id' => 15],
            ['cidade' => 'Sousa', 'estado_id' => 15],
            ['cidade' => 'Sumé', 'estado_id' => 15],
            ['cidade' => 'Taperoá', 'estado_id' => 15],
            ['cidade' => 'Tavares', 'estado_id' => 15],
            ['cidade' => 'Teixeira', 'estado_id' => 15],
            ['cidade' => 'Tenório', 'estado_id' => 15],
            ['cidade' => 'Triunfo', 'estado_id' => 15],
            ['cidade' => 'Uiraúna', 'estado_id' => 15],
            ['cidade' => 'Umbuzeiro', 'estado_id' => 15],
            ['cidade' => 'Várzea', 'estado_id' => 15],
            ['cidade' => 'Vieirópolis', 'estado_id' => 15],
            ['cidade' => 'Vista Serrana', 'estado_id' => 15],
            ['cidade' => 'Zabelê', 'estado_id' => 15]
        ]);

        $this->command->info('Cidades da Paraíba importadas com sucesso!');
    }
}