<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesSaoPauloSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['cidade' => 'Adamantina', 'estado_id' => 25],
            ['cidade' => 'Adolfo', 'estado_id' => 25],
            ['cidade' => 'Aguaí', 'estado_id' => 25],
            ['cidade' => 'Águas da Prata', 'estado_id' => 25],
            ['cidade' => 'Águas de Lindóia', 'estado_id' => 25],
            ['cidade' => 'Águas de Santa Bárbara', 'estado_id' => 25],
            ['cidade' => 'Águas de São Pedro', 'estado_id' => 25],
            ['cidade' => 'Agudos', 'estado_id' => 25],
            ['cidade' => 'Alambari', 'estado_id' => 25],
            ['cidade' => 'Alfredo Marcondes', 'estado_id' => 25],
            ['cidade' => 'Altair', 'estado_id' => 25],
            ['cidade' => 'Altinópolis', 'estado_id' => 25],
            ['cidade' => 'Alto Alegre', 'estado_id' => 25],
            ['cidade' => 'Alumínio', 'estado_id' => 25],
            ['cidade' => 'Álvares Florence', 'estado_id' => 25],
            ['cidade' => 'Álvares Machado', 'estado_id' => 25],
            ['cidade' => 'Álvaro de Carvalho', 'estado_id' => 25],
            ['cidade' => 'Alvinlândia', 'estado_id' => 25],
            ['cidade' => 'Americana', 'estado_id' => 25],
            ['cidade' => 'Américo Brasiliense', 'estado_id' => 25],
            ['cidade' => 'Américo de Campos', 'estado_id' => 25],
            ['cidade' => 'Amparo', 'estado_id' => 25],
            ['cidade' => 'Analândia', 'estado_id' => 25],
            ['cidade' => 'Andradina', 'estado_id' => 25],
            ['cidade' => 'Angatuba', 'estado_id' => 25],
            ['cidade' => 'Anhembi', 'estado_id' => 25],
            ['cidade' => 'Anhumas', 'estado_id' => 25],
            ['cidade' => 'Aparecida', 'estado_id' => 25],
            ['cidade' => 'Aparecida d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Apiaí', 'estado_id' => 25],
            ['cidade' => 'Araçariguama', 'estado_id' => 25],
            ['cidade' => 'Araçatuba', 'estado_id' => 25],
            ['cidade' => 'Araçoiaba da Serra', 'estado_id' => 25],
            ['cidade' => 'Aramina', 'estado_id' => 25],
            ['cidade' => 'Arandu', 'estado_id' => 25],
            ['cidade' => 'Arapeí', 'estado_id' => 25],
            ['cidade' => 'Araraquara', 'estado_id' => 25],
            ['cidade' => 'Araras', 'estado_id' => 25],
            ['cidade' => 'Arco-Íris', 'estado_id' => 25],
            ['cidade' => 'Arealva', 'estado_id' => 25],
            ['cidade' => 'Areias', 'estado_id' => 25],
            ['cidade' => 'Areiópolis', 'estado_id' => 25],
            ['cidade' => 'Ariranha', 'estado_id' => 25],
            ['cidade' => 'Artur Nogueira', 'estado_id' => 25],
            ['cidade' => 'Arujá', 'estado_id' => 25],
            ['cidade' => 'Aspásia', 'estado_id' => 25],
            ['cidade' => 'Assis', 'estado_id' => 25],
            ['cidade' => 'Atibaia', 'estado_id' => 25],
            ['cidade' => 'Auriflama', 'estado_id' => 25],
            ['cidade' => 'Avaí', 'estado_id' => 25],
            ['cidade' => 'Avanhandava', 'estado_id' => 25],
            ['cidade' => 'Avaré', 'estado_id' => 25],
            ['cidade' => 'Bady Bassitt', 'estado_id' => 25],
            ['cidade' => 'Balbinos', 'estado_id' => 25],
            ['cidade' => 'Bálsamo', 'estado_id' => 25],
            ['cidade' => 'Bananal', 'estado_id' => 25],
            ['cidade' => 'Barão de Antonina', 'estado_id' => 25],
            ['cidade' => 'Barbosa', 'estado_id' => 25],
            ['cidade' => 'Bariri', 'estado_id' => 25],
            ['cidade' => 'Barra Bonita', 'estado_id' => 25],
            ['cidade' => 'Barra do Chapéu', 'estado_id' => 25],
            ['cidade' => 'Barra do Turvo', 'estado_id' => 25],
            ['cidade' => 'Barretos', 'estado_id' => 25],
            ['cidade' => 'Barrinha', 'estado_id' => 25],
            ['cidade' => 'Barueri', 'estado_id' => 25],
            ['cidade' => 'Bastos', 'estado_id' => 25],
            ['cidade' => 'Batatais', 'estado_id' => 25],
            ['cidade' => 'Bauru', 'estado_id' => 25],
            ['cidade' => 'Bebedouro', 'estado_id' => 25],
            ['cidade' => 'Bento de Abreu', 'estado_id' => 25],
            ['cidade' => 'Bernardino de Campos', 'estado_id' => 25],
            ['cidade' => 'Bertioga', 'estado_id' => 25],
            ['cidade' => 'Bilac', 'estado_id' => 25],
            ['cidade' => 'Birigui', 'estado_id' => 25],
            ['cidade' => 'Biritiba-Mirim', 'estado_id' => 25],
            ['cidade' => 'Boa Esperança do Sul', 'estado_id' => 25],
            ['cidade' => 'Bocaina', 'estado_id' => 25],
            ['cidade' => 'Bofete', 'estado_id' => 25],
            ['cidade' => 'Boituva', 'estado_id' => 25],
            ['cidade' => 'Bom Jesus dos Perdões', 'estado_id' => 25],
            ['cidade' => 'Bom Sucesso de Itararé', 'estado_id' => 25],
            ['cidade' => 'Borá', 'estado_id' => 25],
            ['cidade' => 'Boracéia', 'estado_id' => 25],
            ['cidade' => 'Borborema', 'estado_id' => 25],
            ['cidade' => 'Borebi', 'estado_id' => 25],
            ['cidade' => 'Botucatu', 'estado_id' => 25],
            ['cidade' => 'Bragança Paulista', 'estado_id' => 25],
            ['cidade' => 'Braúna', 'estado_id' => 25],
            ['cidade' => 'Brejo Alegre', 'estado_id' => 25],
            ['cidade' => 'Brodowski', 'estado_id' => 25],
            ['cidade' => 'Brotas', 'estado_id' => 25],
            ['cidade' => 'Buri', 'estado_id' => 25],
            ['cidade' => 'Buritama', 'estado_id' => 25],
            ['cidade' => 'Buritizal', 'estado_id' => 25],
            ['cidade' => 'Cabrália Paulista', 'estado_id' => 25],
            ['cidade' => 'Cabreúva', 'estado_id' => 25],
            ['cidade' => 'Caçapava', 'estado_id' => 25],
            ['cidade' => 'Cachoeira Paulista', 'estado_id' => 25],
            ['cidade' => 'Caconde', 'estado_id' => 25],
            ['cidade' => 'Cafelândia', 'estado_id' => 25],
            ['cidade' => 'Caiabu', 'estado_id' => 25],
            ['cidade' => 'Caieiras', 'estado_id' => 25],
            ['cidade' => 'Caiuá', 'estado_id' => 25],
            ['cidade' => 'Cajamar', 'estado_id' => 25],
            ['cidade' => 'Cajati', 'estado_id' => 25],
            ['cidade' => 'Cajobi', 'estado_id' => 25],
            ['cidade' => 'Cajuru', 'estado_id' => 25],
            ['cidade' => 'Campina do Monte Alegre', 'estado_id' => 25],
            ['cidade' => 'Campinas', 'estado_id' => 25],
            ['cidade' => 'Campo Limpo Paulista', 'estado_id' => 25],
            ['cidade' => 'Campos do Jordão', 'estado_id' => 25],
            ['cidade' => 'Campos Novos Paulista', 'estado_id' => 25],
            ['cidade' => 'Cananéia', 'estado_id' => 25],
            ['cidade' => 'Canas', 'estado_id' => 25],
            ['cidade' => 'Cândido Mota', 'estado_id' => 25],
            ['cidade' => 'Cândido Rodrigues', 'estado_id' => 25],
            ['cidade' => 'Canitar', 'estado_id' => 25],
            ['cidade' => 'Capão Bonito', 'estado_id' => 25],
            ['cidade' => 'Capela do Alto', 'estado_id' => 25],
            ['cidade' => 'Capivari', 'estado_id' => 25],
            ['cidade' => 'Caraguatatuba', 'estado_id' => 25],
            ['cidade' => 'Carapicuíba', 'estado_id' => 25],
            ['cidade' => 'Cardoso', 'estado_id' => 25],
            ['cidade' => 'Casa Branca', 'estado_id' => 25],
            ['cidade' => 'Cássia dos Coqueiros', 'estado_id' => 25],
            ['cidade' => 'Castilho', 'estado_id' => 25],
            ['cidade' => 'Catanduva', 'estado_id' => 25],
            ['cidade' => 'Catiguá', 'estado_id' => 25],
            ['cidade' => 'Cedral', 'estado_id' => 25],
            ['cidade' => 'Cerqueira César', 'estado_id' => 25],
            ['cidade' => 'Cerquilho', 'estado_id' => 25],
            ['cidade' => 'Cesário Lange', 'estado_id' => 25],
            ['cidade' => 'Charqueada', 'estado_id' => 25],
            ['cidade' => 'Chavantes', 'estado_id' => 25],
            ['cidade' => 'Clementina', 'estado_id' => 25],
            ['cidade' => 'Colina', 'estado_id' => 25],
            ['cidade' => 'Colômbia', 'estado_id' => 25],
            ['cidade' => 'Conchal', 'estado_id' => 25],
            ['cidade' => 'Conchas', 'estado_id' => 25],
            ['cidade' => 'Cordeirópolis', 'estado_id' => 25],
            ['cidade' => 'Coroados', 'estado_id' => 25],
            ['cidade' => 'Coronel Macedo', 'estado_id' => 25],
            ['cidade' => 'Corumbataí', 'estado_id' => 25],
            ['cidade' => 'Cosmópolis', 'estado_id' => 25],
            ['cidade' => 'Cosmorama', 'estado_id' => 25],
            ['cidade' => 'Cotia', 'estado_id' => 25],
            ['cidade' => 'Cravinhos', 'estado_id' => 25],
            ['cidade' => 'Cristais Paulista', 'estado_id' => 25],
            ['cidade' => 'Cruzália', 'estado_id' => 25],
            ['cidade' => 'Cruzeiro', 'estado_id' => 25],
            ['cidade' => 'Cubatão', 'estado_id' => 25],
            ['cidade' => 'Cunha', 'estado_id' => 25],
            ['cidade' => 'Descalvado', 'estado_id' => 25],
            ['cidade' => 'Diadema', 'estado_id' => 25],
            ['cidade' => 'Dirce Reis', 'estado_id' => 25],
            ['cidade' => 'Divinolândia', 'estado_id' => 25],
            ['cidade' => 'Dobrada', 'estado_id' => 25],
            ['cidade' => 'Dois Córregos', 'estado_id' => 25],
            ['cidade' => 'Dolcinópolis', 'estado_id' => 25],
            ['cidade' => 'Dourado', 'estado_id' => 25],
            ['cidade' => 'Dracena', 'estado_id' => 25],
            ['cidade' => 'Duartina', 'estado_id' => 25],
            ['cidade' => 'Dumont', 'estado_id' => 25],
            ['cidade' => 'Echaporã', 'estado_id' => 25],
            ['cidade' => 'Eldorado', 'estado_id' => 25],
            ['cidade' => 'Elias Fausto', 'estado_id' => 25],
            ['cidade' => 'Elisiário', 'estado_id' => 25],
            ['cidade' => 'Embaúba', 'estado_id' => 25],
            ['cidade' => 'Embu', 'estado_id' => 25],
            ['cidade' => 'Embu-Guaçu', 'estado_id' => 25],
            ['cidade' => 'Emilianópolis', 'estado_id' => 25],
            ['cidade' => 'Engenheiro Coelho', 'estado_id' => 25],
            ['cidade' => 'Espírito Santo do Pinhal', 'estado_id' => 25],
            ['cidade' => 'Espírito Santo do Turvo', 'estado_id' => 25],
            ['cidade' => 'Estiva Gerbi', 'estado_id' => 25],
            ['cidade' => 'Estrela d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Estrela do Norte', 'estado_id' => 25],
            ['cidade' => 'Euclides da Cunha Paulista', 'estado_id' => 25],
            ['cidade' => 'Fartura', 'estado_id' => 25],
            ['cidade' => 'Fernando Prestes', 'estado_id' => 25],
            ['cidade' => 'Fernandópolis', 'estado_id' => 25],
            ['cidade' => 'Fernão', 'estado_id' => 25],
            ['cidade' => 'Ferraz de Vasconcelos', 'estado_id' => 25],
            ['cidade' => 'Flora Rica', 'estado_id' => 25],
            ['cidade' => 'Floreal', 'estado_id' => 25],
            ['cidade' => 'Flórida Paulista', 'estado_id' => 25],
            ['cidade' => 'Florínia', 'estado_id' => 25],
            ['cidade' => 'Franca', 'estado_id' => 25],
            ['cidade' => 'Francisco Morato', 'estado_id' => 25],
            ['cidade' => 'Franco da Rocha', 'estado_id' => 25],
            ['cidade' => 'Gabriel Monteiro', 'estado_id' => 25],
            ['cidade' => 'Gália', 'estado_id' => 25],
            ['cidade' => 'Garça', 'estado_id' => 25],
            ['cidade' => 'Gastão Vidigal', 'estado_id' => 25],
            ['cidade' => 'Gavião Peixoto', 'estado_id' => 25],
            ['cidade' => 'General Salgado', 'estado_id' => 25],
            ['cidade' => 'Getulina', 'estado_id' => 25],
            ['cidade' => 'Glicério', 'estado_id' => 25],
            ['cidade' => 'Guaiçara', 'estado_id' => 25],
            ['cidade' => 'Guaimbê', 'estado_id' => 25],
            ['cidade' => 'Guaíra', 'estado_id' => 25],
            ['cidade' => 'Guapiaçu', 'estado_id' => 25],
            ['cidade' => 'Guapiara', 'estado_id' => 25],
            ['cidade' => 'Guará', 'estado_id' => 25],
            ['cidade' => 'Guaraçaí', 'estado_id' => 25],
            ['cidade' => 'Guaraci', 'estado_id' => 25],
            ['cidade' => 'Guarani d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Guarantã', 'estado_id' => 25],
            ['cidade' => 'Guararapes', 'estado_id' => 25],
            ['cidade' => 'Guararema', 'estado_id' => 25],
            ['cidade' => 'Guaratinguetá', 'estado_id' => 25],
            ['cidade' => 'Guareí', 'estado_id' => 25],
            ['cidade' => 'Guariba', 'estado_id' => 25],
            ['cidade' => 'Guarujá', 'estado_id' => 25],
            ['cidade' => 'Guarulhos', 'estado_id' => 25],
            ['cidade' => 'Guatapará', 'estado_id' => 25],
            ['cidade' => 'Guzolândia', 'estado_id' => 25],
            ['cidade' => 'Herculândia', 'estado_id' => 25],
            ['cidade' => 'Holambra', 'estado_id' => 25],
            ['cidade' => 'Hortolândia', 'estado_id' => 25],
            ['cidade' => 'Iacanga', 'estado_id' => 25],
            ['cidade' => 'Iacri', 'estado_id' => 25],
            ['cidade' => 'Iaras', 'estado_id' => 25],
            ['cidade' => 'Ibaté', 'estado_id' => 25],
            ['cidade' => 'Ibirá', 'estado_id' => 25],
            ['cidade' => 'Ibirarema', 'estado_id' => 25],
            ['cidade' => 'Ibitinga', 'estado_id' => 25],
            ['cidade' => 'Ibiúna', 'estado_id' => 25],
            ['cidade' => 'Icém', 'estado_id' => 25],
            ['cidade' => 'Iepê', 'estado_id' => 25],
            ['cidade' => 'Igaraçu do Tietê', 'estado_id' => 25],
            ['cidade' => 'Igarapava', 'estado_id' => 25],
            ['cidade' => 'Igaratá', 'estado_id' => 25],
            ['cidade' => 'Iguape', 'estado_id' => 25],
            ['cidade' => 'Ilha Comprida', 'estado_id' => 25],
            ['cidade' => 'Ilha Solteira', 'estado_id' => 25],
            ['cidade' => 'Ilhabela', 'estado_id' => 25],
            ['cidade' => 'Indaiatuba', 'estado_id' => 25],
            ['cidade' => 'Indiana', 'estado_id' => 25],
            ['cidade' => 'Indiaporã', 'estado_id' => 25],
            ['cidade' => 'Inúbia Paulista', 'estado_id' => 25],
            ['cidade' => 'Ipaussu', 'estado_id' => 25],
            ['cidade' => 'Iperó', 'estado_id' => 25],
            ['cidade' => 'Ipeúna', 'estado_id' => 25],
            ['cidade' => 'Ipiguá', 'estado_id' => 25],
            ['cidade' => 'Iporanga', 'estado_id' => 25],
            ['cidade' => 'Ipuã', 'estado_id' => 25],
            ['cidade' => 'Iracemápolis', 'estado_id' => 25],
            ['cidade' => 'Irapuã', 'estado_id' => 25],
            ['cidade' => 'Irapuru', 'estado_id' => 25],
            ['cidade' => 'Itaberá', 'estado_id' => 25],
            ['cidade' => 'Itaí', 'estado_id' => 25],
            ['cidade' => 'Itajobi', 'estado_id' => 25],
            ['cidade' => 'Itaju', 'estado_id' => 25],
            ['cidade' => 'Itanhaém', 'estado_id' => 25],
            ['cidade' => 'Itaóca', 'estado_id' => 25],
            ['cidade' => 'Itapecerica da Serra', 'estado_id' => 25],
            ['cidade' => 'Itapetininga', 'estado_id' => 25],
            ['cidade' => 'Itapeva', 'estado_id' => 25],
            ['cidade' => 'Itapevi', 'estado_id' => 25],
            ['cidade' => 'Itapira', 'estado_id' => 25],
            ['cidade' => 'Itapirapuã Paulista', 'estado_id' => 25],
            ['cidade' => 'Itápolis', 'estado_id' => 25],
            ['cidade' => 'Itaporanga', 'estado_id' => 25],
            ['cidade' => 'Itapuí', 'estado_id' => 25],
            ['cidade' => 'Itapura', 'estado_id' => 25],
            ['cidade' => 'Itaquaquecetuba', 'estado_id' => 25],
            ['cidade' => 'Itararé', 'estado_id' => 25],
            ['cidade' => 'Itariri', 'estado_id' => 25],
            ['cidade' => 'Itatiba', 'estado_id' => 25],
            ['cidade' => 'Itatinga', 'estado_id' => 25],
            ['cidade' => 'Itirapina', 'estado_id' => 25],
            ['cidade' => 'Itirapuã', 'estado_id' => 25],
            ['cidade' => 'Itobi', 'estado_id' => 25],
            ['cidade' => 'Itu', 'estado_id' => 25],
            ['cidade' => 'Itupeva', 'estado_id' => 25],
            ['cidade' => 'Ituverava', 'estado_id' => 25],
            ['cidade' => 'Jaborandi', 'estado_id' => 25],
            ['cidade' => 'Jaboticabal', 'estado_id' => 25],
            ['cidade' => 'Jacareí', 'estado_id' => 25],
            ['cidade' => 'Jaci', 'estado_id' => 25],
            ['cidade' => 'Jacupiranga', 'estado_id' => 25],
            ['cidade' => 'Jaguariúna', 'estado_id' => 25],
            ['cidade' => 'Jales', 'estado_id' => 25],
            ['cidade' => 'Jambeiro', 'estado_id' => 25],
            ['cidade' => 'Jandira', 'estado_id' => 25],
            ['cidade' => 'Jardinópolis', 'estado_id' => 25],
            ['cidade' => 'Jarinu', 'estado_id' => 25],
            ['cidade' => 'Jaú', 'estado_id' => 25],
            ['cidade' => 'Jeriquara', 'estado_id' => 25],
            ['cidade' => 'Joanópolis', 'estado_id' => 25],
            ['cidade' => 'João Ramalho', 'estado_id' => 25],
            ['cidade' => 'José Bonifácio', 'estado_id' => 25],
            ['cidade' => 'Júlio Mesquita', 'estado_id' => 25],
            ['cidade' => 'Jumirim', 'estado_id' => 25],
            ['cidade' => 'Jundiaí', 'estado_id' => 25],
            ['cidade' => 'Junqueirópolis', 'estado_id' => 25],
            ['cidade' => 'Juquiá', 'estado_id' => 25],
            ['cidade' => 'Juquitiba', 'estado_id' => 25],
            ['cidade' => 'Lagoinha', 'estado_id' => 25],
            ['cidade' => 'Laranjal Paulista', 'estado_id' => 25],
            ['cidade' => 'Lavínia', 'estado_id' => 25],
            ['cidade' => 'Lavrinhas', 'estado_id' => 25],
            ['cidade' => 'Leme', 'estado_id' => 25],
            ['cidade' => 'Lençóis Paulista', 'estado_id' => 25],
            ['cidade' => 'Limeira', 'estado_id' => 25],
            ['cidade' => 'Lindóia', 'estado_id' => 25],
            ['cidade' => 'Lins', 'estado_id' => 25],
            ['cidade' => 'Lorena', 'estado_id' => 25],
            ['cidade' => 'Lourdes', 'estado_id' => 25],
            ['cidade' => 'Louveira', 'estado_id' => 25],
            ['cidade' => 'Lucélia', 'estado_id' => 25],
            ['cidade' => 'Lucianópolis', 'estado_id' => 25],
            ['cidade' => 'Luís Antônio', 'estado_id' => 25],
            ['cidade' => 'Luiziânia', 'estado_id' => 25],
            ['cidade' => 'Lupércio', 'estado_id' => 25],
            ['cidade' => 'Lutécia', 'estado_id' => 25],
            ['cidade' => 'Macatuba', 'estado_id' => 25],
            ['cidade' => 'Macaubal', 'estado_id' => 25],
            ['cidade' => 'Macedônia', 'estado_id' => 25],
            ['cidade' => 'Magda', 'estado_id' => 25],
            ['cidade' => 'Mairinque', 'estado_id' => 25],
            ['cidade' => 'Mairiporã', 'estado_id' => 25],
            ['cidade' => 'Manduri', 'estado_id' => 25],
            ['cidade' => 'Marabá Paulista', 'estado_id' => 25],
            ['cidade' => 'Maracaí', 'estado_id' => 25],
            ['cidade' => 'Marapoama', 'estado_id' => 25],
            ['cidade' => 'Mariápolis', 'estado_id' => 25],
            ['cidade' => 'Marília', 'estado_id' => 25],
            ['cidade' => 'Marinópolis', 'estado_id' => 25],
            ['cidade' => 'Martinópolis', 'estado_id' => 25],
            ['cidade' => 'Matão', 'estado_id' => 25],
            ['cidade' => 'Mauá', 'estado_id' => 25],
            ['cidade' => 'Mendonça', 'estado_id' => 25],
            ['cidade' => 'Meridiano', 'estado_id' => 25],
            ['cidade' => 'Mesópolis', 'estado_id' => 25],
            ['cidade' => 'Miguelópolis', 'estado_id' => 25],
            ['cidade' => 'Mineiros do Tietê', 'estado_id' => 25],
            ['cidade' => 'Mira Estrela', 'estado_id' => 25],
            ['cidade' => 'Miracatu', 'estado_id' => 25],
            ['cidade' => 'Mirandópolis', 'estado_id' => 25],
            ['cidade' => 'Mirante do Paranapanema', 'estado_id' => 25],
            ['cidade' => 'Mirassol', 'estado_id' => 25],
            ['cidade' => 'Mirassolândia', 'estado_id' => 25],
            ['cidade' => 'Mococa', 'estado_id' => 25],
            ['cidade' => 'Mogi das Cruzes', 'estado_id' => 25],
            ['cidade' => 'Mogi Guaçu', 'estado_id' => 25],
            ['cidade' => 'Moji Mirim', 'estado_id' => 25],
            ['cidade' => 'Mombuca', 'estado_id' => 25],
            ['cidade' => 'Monções', 'estado_id' => 25],
            ['cidade' => 'Mongaguá', 'estado_id' => 25],
            ['cidade' => 'Monte Alegre do Sul', 'estado_id' => 25],
            ['cidade' => 'Monte Alto', 'estado_id' => 25],
            ['cidade' => 'Monte Aprazível', 'estado_id' => 25],
            ['cidade' => 'Monte Azul Paulista', 'estado_id' => 25],
            ['cidade' => 'Monte Castelo', 'estado_id' => 25],
            ['cidade' => 'Monte Mor', 'estado_id' => 25],
            ['cidade' => 'Monteiro Lobato', 'estado_id' => 25],
            ['cidade' => 'Morro Agudo', 'estado_id' => 25],
            ['cidade' => 'Morungaba', 'estado_id' => 25],
            ['cidade' => 'Motuca', 'estado_id' => 25],
            ['cidade' => 'Murutinga do Sul', 'estado_id' => 25],
            ['cidade' => 'Nantes', 'estado_id' => 25],
            ['cidade' => 'Narandiba', 'estado_id' => 25],
            ['cidade' => 'Natividade da Serra', 'estado_id' => 25],
            ['cidade' => 'Nazaré Paulista', 'estado_id' => 25],
            ['cidade' => 'Neves Paulista', 'estado_id' => 25],
            ['cidade' => 'Nhandeara', 'estado_id' => 25],
            ['cidade' => 'Nipoã', 'estado_id' => 25],
            ['cidade' => 'Nova Aliança', 'estado_id' => 25],
            ['cidade' => 'Nova Campina', 'estado_id' => 25],
            ['cidade' => 'Nova Canaã Paulista', 'estado_id' => 25],
            ['cidade' => 'Nova Castilho', 'estado_id' => 25],
            ['cidade' => 'Nova Europa', 'estado_id' => 25],
            ['cidade' => 'Nova Granada', 'estado_id' => 25],
            ['cidade' => 'Nova Guataporanga', 'estado_id' => 25],
            ['cidade' => 'Nova Independência', 'estado_id' => 25],
            ['cidade' => 'Nova Luzitânia', 'estado_id' => 25],
            ['cidade' => 'Nova Odessa', 'estado_id' => 25],
            ['cidade' => 'Novais', 'estado_id' => 25],
            ['cidade' => 'Novo Horizonte', 'estado_id' => 25],
            ['cidade' => 'Nuporanga', 'estado_id' => 25],
            ['cidade' => 'Ocauçu', 'estado_id' => 25],
            ['cidade' => 'Óleo', 'estado_id' => 25],
            ['cidade' => 'Olímpia', 'estado_id' => 25],
            ['cidade' => 'Onda Verde', 'estado_id' => 25],
            ['cidade' => 'Oriente', 'estado_id' => 25],
            ['cidade' => 'Orindiúva', 'estado_id' => 25],
            ['cidade' => 'Orlândia', 'estado_id' => 25],
            ['cidade' => 'Osasco', 'estado_id' => 25],
            ['cidade' => 'Oscar Bressane', 'estado_id' => 25],
            ['cidade' => 'Osvaldo Cruz', 'estado_id' => 25],
            ['cidade' => 'Ourinhos', 'estado_id' => 25],
            ['cidade' => 'Ouro Verde', 'estado_id' => 25],
            ['cidade' => 'Ouroeste', 'estado_id' => 25],
            ['cidade' => 'Pacaembu', 'estado_id' => 25],
            ['cidade' => 'Palestina', 'estado_id' => 25],
            ['cidade' => 'Palmares Paulista', 'estado_id' => 25],
            ['cidade' => 'Palmeira d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Palmital', 'estado_id' => 25],
            ['cidade' => 'Panorama', 'estado_id' => 25],
            ['cidade' => 'Paraguaçu Paulista', 'estado_id' => 25],
            ['cidade' => 'Paraibuna', 'estado_id' => 25],
            ['cidade' => 'Paraíso', 'estado_id' => 25],
            ['cidade' => 'Paranapanema', 'estado_id' => 25],
            ['cidade' => 'Paranapuã', 'estado_id' => 25],
            ['cidade' => 'Parapuã', 'estado_id' => 25],
            ['cidade' => 'Pardinho', 'estado_id' => 25],
            ['cidade' => 'Pariquera-Açu', 'estado_id' => 25],
            ['cidade' => 'Parisi', 'estado_id' => 25],
            ['cidade' => 'Patrocínio Paulista', 'estado_id' => 25],
            ['cidade' => 'Paulicéia', 'estado_id' => 25],
            ['cidade' => 'Paulínia', 'estado_id' => 25],
            ['cidade' => 'Paulistânia', 'estado_id' => 25],
            ['cidade' => 'Paulo de Faria', 'estado_id' => 25],
            ['cidade' => 'Pederneiras', 'estado_id' => 25],
            ['cidade' => 'Pedra Bela', 'estado_id' => 25],
            ['cidade' => 'Pedranópolis', 'estado_id' => 25],
            ['cidade' => 'Pedregulho', 'estado_id' => 25],
            ['cidade' => 'Pedreira', 'estado_id' => 25],
            ['cidade' => 'Pedrinhas Paulista', 'estado_id' => 25],
            ['cidade' => 'Pedro de Toledo', 'estado_id' => 25],
            ['cidade' => 'Penápolis', 'estado_id' => 25],
            ['cidade' => 'Pereira Barreto', 'estado_id' => 25],
            ['cidade' => 'Pereiras', 'estado_id' => 25],
            ['cidade' => 'Peruíbe', 'estado_id' => 25],
            ['cidade' => 'Piacatu', 'estado_id' => 25],
            ['cidade' => 'Piedade', 'estado_id' => 25],
            ['cidade' => 'Pilar do Sul', 'estado_id' => 25],
            ['cidade' => 'Pindamonhangaba', 'estado_id' => 25],
            ['cidade' => 'Pindorama', 'estado_id' => 25],
            ['cidade' => 'Pinhalzinho', 'estado_id' => 25],
            ['cidade' => 'Piquerobi', 'estado_id' => 25],
            ['cidade' => 'Piquete', 'estado_id' => 25],
            ['cidade' => 'Piracaia', 'estado_id' => 25],
            ['cidade' => 'Piracicaba', 'estado_id' => 25],
            ['cidade' => 'Piraju', 'estado_id' => 25],
            ['cidade' => 'Pirajuí', 'estado_id' => 25],
            ['cidade' => 'Pirangi', 'estado_id' => 25],
            ['cidade' => 'Pirapora do Bom Jesus', 'estado_id' => 25],
            ['cidade' => 'Pirapozinho', 'estado_id' => 25],
            ['cidade' => 'Pirassununga', 'estado_id' => 25],
            ['cidade' => 'Piratininga', 'estado_id' => 25],
            ['cidade' => 'Pitangueiras', 'estado_id' => 25],
            ['cidade' => 'Planalto', 'estado_id' => 25],
            ['cidade' => 'Platina', 'estado_id' => 25],
            ['cidade' => 'Poá', 'estado_id' => 25],
            ['cidade' => 'Poloni', 'estado_id' => 25],
            ['cidade' => 'Pompéia', 'estado_id' => 25],
            ['cidade' => 'Pongaí', 'estado_id' => 25],
            ['cidade' => 'Pontal', 'estado_id' => 25],
            ['cidade' => 'Pontalinda', 'estado_id' => 25],
            ['cidade' => 'Pontes Gestal', 'estado_id' => 25],
            ['cidade' => 'Populina', 'estado_id' => 25],
            ['cidade' => 'Porangaba', 'estado_id' => 25],
            ['cidade' => 'Porto Feliz', 'estado_id' => 25],
            ['cidade' => 'Porto Ferreira', 'estado_id' => 25],
            ['cidade' => 'Potim', 'estado_id' => 25],
            ['cidade' => 'Potirendaba', 'estado_id' => 25],
            ['cidade' => 'Pracinha', 'estado_id' => 25],
            ['cidade' => 'Pradópolis', 'estado_id' => 25],
            ['cidade' => 'Praia Grande', 'estado_id' => 25],
            ['cidade' => 'Pratânia', 'estado_id' => 25],
            ['cidade' => 'Presidente Alves', 'estado_id' => 25],
            ['cidade' => 'Presidente Bernardes', 'estado_id' => 25],
            ['cidade' => 'Presidente Epitácio', 'estado_id' => 25],
            ['cidade' => 'Presidente Prudente', 'estado_id' => 25],
            ['cidade' => 'Presidente Venceslau', 'estado_id' => 25],
            ['cidade' => 'Promissão', 'estado_id' => 25],
            ['cidade' => 'Quadra', 'estado_id' => 25],
            ['cidade' => 'Quatá', 'estado_id' => 25],
            ['cidade' => 'Queiroz', 'estado_id' => 25],
            ['cidade' => 'Queluz', 'estado_id' => 25],
            ['cidade' => 'Quintana', 'estado_id' => 25],
            ['cidade' => 'Rafard', 'estado_id' => 25],
            ['cidade' => 'Rancharia', 'estado_id' => 25],
            ['cidade' => 'Redenção da Serra', 'estado_id' => 25],
            ['cidade' => 'Regente Feijó', 'estado_id' => 25],
            ['cidade' => 'Reginópolis', 'estado_id' => 25],
            ['cidade' => 'Registro', 'estado_id' => 25],
            ['cidade' => 'Restinga', 'estado_id' => 25],
            ['cidade' => 'Ribeira', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Bonito', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Branco', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Corrente', 'estado_id' => 25],
            ['cidade' => 'Ribeirão do Sul', 'estado_id' => 25],
            ['cidade' => 'Ribeirão dos Índios', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Grande', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Pires', 'estado_id' => 25],
            ['cidade' => 'Ribeirão Preto', 'estado_id' => 25],
            ['cidade' => 'Rifaina', 'estado_id' => 25],
            ['cidade' => 'Rincão', 'estado_id' => 25],
            ['cidade' => 'Rinópolis', 'estado_id' => 25],
            ['cidade' => 'Rio Claro', 'estado_id' => 25],
            ['cidade' => 'Rio das Pedras', 'estado_id' => 25],
            ['cidade' => 'Rio Grande da Serra', 'estado_id' => 25],
            ['cidade' => 'Riolândia', 'estado_id' => 25],
            ['cidade' => 'Riversul', 'estado_id' => 25],
            ['cidade' => 'Rosana', 'estado_id' => 25],
            ['cidade' => 'Roseira', 'estado_id' => 25]
        ]);

		DB::table('cidades')->insert([
			['cidade' => 'Rubiácea', 'estado_id' => 25],
            ['cidade' => 'Rubinéia', 'estado_id' => 25],
            ['cidade' => 'Sabino', 'estado_id' => 25],
            ['cidade' => 'Sagres', 'estado_id' => 25],
            ['cidade' => 'Sales', 'estado_id' => 25],
            ['cidade' => 'Sales Oliveira', 'estado_id' => 25],
            ['cidade' => 'Salesópolis', 'estado_id' => 25],
            ['cidade' => 'Salmourão', 'estado_id' => 25],
            ['cidade' => 'Saltinho', 'estado_id' => 25],
            ['cidade' => 'Salto', 'estado_id' => 25],
            ['cidade' => 'Salto de Pirapora', 'estado_id' => 25],
            ['cidade' => 'Salto Grande', 'estado_id' => 25],
            ['cidade' => 'Sandovalina', 'estado_id' => 25],
            ['cidade' => 'Santa Adélia', 'estado_id' => 25],
            ['cidade' => 'Santa Albertina', 'estado_id' => 25],
            ['cidade' => 'Santa Bárbara d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Santa Branca', 'estado_id' => 25],
            ['cidade' => 'Santa Clara d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Santa Cruz da Conceição', 'estado_id' => 25],
            ['cidade' => 'Santa Cruz da Esperança', 'estado_id' => 25],
            ['cidade' => 'Santa Cruz das Palmeiras', 'estado_id' => 25],
            ['cidade' => 'Santa Cruz do Rio Pardo', 'estado_id' => 25],
            ['cidade' => 'Santa Ernestina', 'estado_id' => 25],
            ['cidade' => 'Santa Fé do Sul', 'estado_id' => 25],
            ['cidade' => 'Santa Gertrudes', 'estado_id' => 25],
            ['cidade' => 'Santa Isabel', 'estado_id' => 25],
            ['cidade' => 'Santa Lúcia', 'estado_id' => 25],
            ['cidade' => 'Santa Maria da Serra', 'estado_id' => 25],
            ['cidade' => 'Santa Mercedes', 'estado_id' => 25],
            ['cidade' => 'Santa Rita d`Oeste', 'estado_id' => 25],
            ['cidade' => 'Santa Rita do Passa Quatro', 'estado_id' => 25],
            ['cidade' => 'Santa Rosa de Viterbo', 'estado_id' => 25],
            ['cidade' => 'Santa Salete', 'estado_id' => 25],
            ['cidade' => 'Santana da Ponte Pensa', 'estado_id' => 25],
            ['cidade' => 'Santana de Parnaíba', 'estado_id' => 25],
            ['cidade' => 'Santo Anastácio', 'estado_id' => 25],
            ['cidade' => 'Santo André', 'estado_id' => 25],
            ['cidade' => 'Santo Antônio da Alegria', 'estado_id' => 25],
            ['cidade' => 'Santo Antônio de Posse', 'estado_id' => 25],
            ['cidade' => 'Santo Antônio do Aracanguá', 'estado_id' => 25],
            ['cidade' => 'Santo Antônio do Jardim', 'estado_id' => 25],
            ['cidade' => 'Santo Antônio do Pinhal', 'estado_id' => 25],
            ['cidade' => 'Santo Expedito', 'estado_id' => 25],
            ['cidade' => 'Santópolis do Aguapeí', 'estado_id' => 25],
            ['cidade' => 'Santos', 'estado_id' => 25],
            ['cidade' => 'São Bento do Sapucaí', 'estado_id' => 25],
            ['cidade' => 'São Bernardo do Campo', 'estado_id' => 25],
            ['cidade' => 'São Caetano do Sul', 'estado_id' => 25],
            ['cidade' => 'São Carlos', 'estado_id' => 25],
            ['cidade' => 'São Francisco', 'estado_id' => 25],
            ['cidade' => 'São João da Boa Vista', 'estado_id' => 25],
            ['cidade' => 'São João das Duas Pontes', 'estado_id' => 25],
            ['cidade' => 'São João de Iracema', 'estado_id' => 25],
            ['cidade' => 'São João do Pau d`Alho', 'estado_id' => 25],
            ['cidade' => 'São Joaquim da Barra', 'estado_id' => 25],
            ['cidade' => 'São José da Bela Vista', 'estado_id' => 25],
            ['cidade' => 'São José do Barreiro', 'estado_id' => 25],
            ['cidade' => 'São José do Rio Pardo', 'estado_id' => 25],
            ['cidade' => 'São José do Rio Preto', 'estado_id' => 25],
            ['cidade' => 'São José dos Campos', 'estado_id' => 25],
            ['cidade' => 'São Lourenço da Serra', 'estado_id' => 25],
            ['cidade' => 'São Luís do Paraitinga', 'estado_id' => 25],
            ['cidade' => 'São Manuel', 'estado_id' => 25],
            ['cidade' => 'São Miguel Arcanjo', 'estado_id' => 25],
            ['cidade' => 'São Paulo', 'estado_id' => 25],
            ['cidade' => 'São Pedro', 'estado_id' => 25],
            ['cidade' => 'São Pedro do Turvo', 'estado_id' => 25],
            ['cidade' => 'São Roque', 'estado_id' => 25],
            ['cidade' => 'São Sebastião', 'estado_id' => 25],
            ['cidade' => 'São Sebastião da Grama', 'estado_id' => 25],
            ['cidade' => 'São Simão', 'estado_id' => 25],
            ['cidade' => 'São Vicente', 'estado_id' => 25],
            ['cidade' => 'Sarapuí', 'estado_id' => 25],
            ['cidade' => 'Sarutaiá', 'estado_id' => 25],
            ['cidade' => 'Sebastianópolis do Sul', 'estado_id' => 25],
            ['cidade' => 'Serra Azul', 'estado_id' => 25],
            ['cidade' => 'Serra Negra', 'estado_id' => 25],
            ['cidade' => 'Serrana', 'estado_id' => 25],
            ['cidade' => 'Sertãozinho', 'estado_id' => 25],
            ['cidade' => 'Sete Barras', 'estado_id' => 25],
            ['cidade' => 'Severínia', 'estado_id' => 25],
            ['cidade' => 'Silveiras', 'estado_id' => 25],
            ['cidade' => 'Socorro', 'estado_id' => 25],
            ['cidade' => 'Sorocaba', 'estado_id' => 25],
            ['cidade' => 'Sud Mennucci', 'estado_id' => 25],
            ['cidade' => 'Sumaré', 'estado_id' => 25],
            ['cidade' => 'Suzanápolis', 'estado_id' => 25],
            ['cidade' => 'Suzano', 'estado_id' => 25],
            ['cidade' => 'Tabapuã', 'estado_id' => 25],
            ['cidade' => 'Tabatinga', 'estado_id' => 25],
            ['cidade' => 'Taboão da Serra', 'estado_id' => 25],
            ['cidade' => 'Taciba', 'estado_id' => 25],
            ['cidade' => 'Taguaí', 'estado_id' => 25],
            ['cidade' => 'Taiaçu', 'estado_id' => 25],
            ['cidade' => 'Taiúva', 'estado_id' => 25],
            ['cidade' => 'Tambaú', 'estado_id' => 25],
            ['cidade' => 'Tanabi', 'estado_id' => 25],
            ['cidade' => 'Tapiraí', 'estado_id' => 25],
            ['cidade' => 'Tapiratiba', 'estado_id' => 25],
            ['cidade' => 'Taquaral', 'estado_id' => 25],
            ['cidade' => 'Taquaritinga', 'estado_id' => 25],
            ['cidade' => 'Taquarituba', 'estado_id' => 25],
            ['cidade' => 'Taquarivaí', 'estado_id' => 25],
            ['cidade' => 'Tarabai', 'estado_id' => 25],
            ['cidade' => 'Tarumã', 'estado_id' => 25],
            ['cidade' => 'Tatuí', 'estado_id' => 25],
            ['cidade' => 'Taubaté', 'estado_id' => 25],
            ['cidade' => 'Tejupá', 'estado_id' => 25],
            ['cidade' => 'Teodoro Sampaio', 'estado_id' => 25],
            ['cidade' => 'Terra Roxa', 'estado_id' => 25],
            ['cidade' => 'Tietê', 'estado_id' => 25],
            ['cidade' => 'Timburi', 'estado_id' => 25],
            ['cidade' => 'Torre de Pedra', 'estado_id' => 25],
            ['cidade' => 'Torrinha', 'estado_id' => 25],
            ['cidade' => 'Trabiju', 'estado_id' => 25],
            ['cidade' => 'Tremembé', 'estado_id' => 25],
            ['cidade' => 'Três Fronteiras', 'estado_id' => 25],
            ['cidade' => 'Tuiuti', 'estado_id' => 25],
            ['cidade' => 'Tupã', 'estado_id' => 25],
            ['cidade' => 'Tupi Paulista', 'estado_id' => 25],
            ['cidade' => 'Turiúba', 'estado_id' => 25],
            ['cidade' => 'Turmalina', 'estado_id' => 25],
            ['cidade' => 'Ubarana', 'estado_id' => 25],
            ['cidade' => 'Ubatuba', 'estado_id' => 25],
            ['cidade' => 'Ubirajara', 'estado_id' => 25],
            ['cidade' => 'Uchoa', 'estado_id' => 25],
            ['cidade' => 'União Paulista', 'estado_id' => 25],
            ['cidade' => 'Urânia', 'estado_id' => 25],
            ['cidade' => 'Uru', 'estado_id' => 25],
            ['cidade' => 'Urupês', 'estado_id' => 25],
            ['cidade' => 'Valentim Gentil', 'estado_id' => 25],
            ['cidade' => 'Valinhos', 'estado_id' => 25],
            ['cidade' => 'Valparaíso', 'estado_id' => 25],
            ['cidade' => 'Vargem', 'estado_id' => 25],
            ['cidade' => 'Vargem Grande do Sul', 'estado_id' => 25],
            ['cidade' => 'Vargem Grande Paulista', 'estado_id' => 25],
            ['cidade' => 'Várzea Paulista', 'estado_id' => 25],
            ['cidade' => 'Vera Cruz', 'estado_id' => 25],
            ['cidade' => 'Vinhedo', 'estado_id' => 25],
            ['cidade' => 'Viradouro', 'estado_id' => 25],
            ['cidade' => 'Vista Alegre do Alto', 'estado_id' => 25],
            ['cidade' => 'Vitória Brasil', 'estado_id' => 25],
            ['cidade' => 'Votorantim', 'estado_id' => 25],
            ['cidade' => 'Votuporanga', 'estado_id' => 25],
            ['cidade' => 'Zacarias', 'estado_id' => 25]
		]);

        $this->command->info('Cidades de São Paulo importadas com sucesso!');
    }
}