<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesMaranhaoSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['cidade' => 'Açailândia', 'estado_id' => 10],
            ['cidade' => 'Afonso Cunha', 'estado_id' => 10],
            ['cidade' => 'Água Doce do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Alcântara', 'estado_id' => 10],
            ['cidade' => 'Aldeias Altas', 'estado_id' => 10],
            ['cidade' => 'Altamira do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Alto Alegre do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Alto Alegre do Pindaré', 'estado_id' => 10],
            ['cidade' => 'Alto Parnaíba', 'estado_id' => 10],
            ['cidade' => 'Amapá do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Amarante do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Anajatuba', 'estado_id' => 10],
            ['cidade' => 'Anapurus', 'estado_id' => 10],
            ['cidade' => 'Apicum-Açu', 'estado_id' => 10],
            ['cidade' => 'Araguanã', 'estado_id' => 10],
            ['cidade' => 'Araioses', 'estado_id' => 10],
            ['cidade' => 'Arame', 'estado_id' => 10],
            ['cidade' => 'Arari', 'estado_id' => 10],
            ['cidade' => 'Axixá', 'estado_id' => 10],
            ['cidade' => 'Bacabal', 'estado_id' => 10],
            ['cidade' => 'Bacabeira', 'estado_id' => 10],
            ['cidade' => 'Bacuri', 'estado_id' => 10],
            ['cidade' => 'Bacurituba', 'estado_id' => 10],
            ['cidade' => 'Balsas', 'estado_id' => 10],
            ['cidade' => 'Barão de Grajaú', 'estado_id' => 10],
            ['cidade' => 'Barra do Corda', 'estado_id' => 10],
            ['cidade' => 'Barreirinhas', 'estado_id' => 10],
            ['cidade' => 'Bela Vista do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Belágua', 'estado_id' => 10],
            ['cidade' => 'Benedito Leite', 'estado_id' => 10],
            ['cidade' => 'Bequimão', 'estado_id' => 10],
            ['cidade' => 'Bernardo do Mearim', 'estado_id' => 10],
            ['cidade' => 'Boa Vista do Gurupi', 'estado_id' => 10],
            ['cidade' => 'Bom Jardim', 'estado_id' => 10],
            ['cidade' => 'Bom Jesus das Selvas', 'estado_id' => 10],
            ['cidade' => 'Bom Lugar', 'estado_id' => 10],
            ['cidade' => 'Brejo', 'estado_id' => 10],
            ['cidade' => 'Brejo de Areia', 'estado_id' => 10],
            ['cidade' => 'Buriti', 'estado_id' => 10],
            ['cidade' => 'Buriti Bravo', 'estado_id' => 10],
            ['cidade' => 'Buriticupu', 'estado_id' => 10],
            ['cidade' => 'Buritirana', 'estado_id' => 10],
            ['cidade' => 'Cachoeira Grande', 'estado_id' => 10],
            ['cidade' => 'Cajapió', 'estado_id' => 10],
            ['cidade' => 'Cajari', 'estado_id' => 10],
            ['cidade' => 'Campestre do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Cândido Mendes', 'estado_id' => 10],
            ['cidade' => 'Cantanhede', 'estado_id' => 10],
            ['cidade' => 'Capinzal do Norte', 'estado_id' => 10],
            ['cidade' => 'Carolina', 'estado_id' => 10],
            ['cidade' => 'Carutapera', 'estado_id' => 10],
            ['cidade' => 'Caxias', 'estado_id' => 10],
            ['cidade' => 'Cedral', 'estado_id' => 10],
            ['cidade' => 'Central do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Centro do Guilherme', 'estado_id' => 10],
            ['cidade' => 'Centro Novo do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Chapadinha', 'estado_id' => 10],
            ['cidade' => 'Cidelândia', 'estado_id' => 10],
            ['cidade' => 'Codó', 'estado_id' => 10],
            ['cidade' => 'Coelho Neto', 'estado_id' => 10],
            ['cidade' => 'Colinas', 'estado_id' => 10],
            ['cidade' => 'Conceição do Lago-Açu', 'estado_id' => 10],
            ['cidade' => 'Coroatá', 'estado_id' => 10],
            ['cidade' => 'Cururupu', 'estado_id' => 10],
            ['cidade' => 'Davinópolis', 'estado_id' => 10],
            ['cidade' => 'Dom Pedro', 'estado_id' => 10],
            ['cidade' => 'Duque Bacelar', 'estado_id' => 10],
            ['cidade' => 'Esperantinópolis', 'estado_id' => 10],
            ['cidade' => 'Estreito', 'estado_id' => 10],
            ['cidade' => 'Feira Nova do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Fernando Falcão', 'estado_id' => 10],
            ['cidade' => 'Formosa da Serra Negra', 'estado_id' => 10],
            ['cidade' => 'Fortaleza dos Nogueiras', 'estado_id' => 10],
            ['cidade' => 'Fortuna', 'estado_id' => 10],
            ['cidade' => 'Godofredo Viana', 'estado_id' => 10],
            ['cidade' => 'Gonçalves Dias', 'estado_id' => 10],
            ['cidade' => 'Governador Archer', 'estado_id' => 10],
            ['cidade' => 'Governador Edison Lobão', 'estado_id' => 10],
            ['cidade' => 'Governador Eugênio Barros', 'estado_id' => 10],
            ['cidade' => 'Governador Luiz Rocha', 'estado_id' => 10],
            ['cidade' => 'Governador Newton Bello', 'estado_id' => 10],
            ['cidade' => 'Governador Nunes Freire', 'estado_id' => 10],
            ['cidade' => 'Graça Aranha', 'estado_id' => 10],
            ['cidade' => 'Grajaú', 'estado_id' => 10],
            ['cidade' => 'Guimarães', 'estado_id' => 10],
            ['cidade' => 'Humberto de Campos', 'estado_id' => 10],
            ['cidade' => 'Icatu', 'estado_id' => 10],
            ['cidade' => 'Igarapé do Meio', 'estado_id' => 10],
            ['cidade' => 'Igarapé Grande', 'estado_id' => 10],
            ['cidade' => 'Imperatriz', 'estado_id' => 10],
            ['cidade' => 'Itaipava do Grajaú', 'estado_id' => 10],
            ['cidade' => 'Itapecuru Mirim', 'estado_id' => 10],
            ['cidade' => 'Itinga do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Jatobá', 'estado_id' => 10],
            ['cidade' => 'Jenipapo dos Vieiras', 'estado_id' => 10],
            ['cidade' => 'João Lisboa', 'estado_id' => 10],
            ['cidade' => 'Joselândia', 'estado_id' => 10],
            ['cidade' => 'Junco do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Lago da Pedra', 'estado_id' => 10],
            ['cidade' => 'Lago do Junco', 'estado_id' => 10],
            ['cidade' => 'Lago dos Rodrigues', 'estado_id' => 10],
            ['cidade' => 'Lago Verde', 'estado_id' => 10],
            ['cidade' => 'Lagoa do Mato', 'estado_id' => 10],
            ['cidade' => 'Lagoa Grande do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Lajeado Novo', 'estado_id' => 10],
            ['cidade' => 'Lima Campos', 'estado_id' => 10],
            ['cidade' => 'Loreto', 'estado_id' => 10],
            ['cidade' => 'Luís Domingues', 'estado_id' => 10],
            ['cidade' => 'Magalhães de Almeida', 'estado_id' => 10],
            ['cidade' => 'Maracaçumé', 'estado_id' => 10],
            ['cidade' => 'Marajá do Sena', 'estado_id' => 10],
            ['cidade' => 'Maranhãozinho', 'estado_id' => 10],
            ['cidade' => 'Mata Roma', 'estado_id' => 10],
            ['cidade' => 'Matinha', 'estado_id' => 10],
            ['cidade' => 'Matões', 'estado_id' => 10],
            ['cidade' => 'Matões do Norte', 'estado_id' => 10],
            ['cidade' => 'Milagres do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Mirador', 'estado_id' => 10],
            ['cidade' => 'Miranda do Norte', 'estado_id' => 10],
            ['cidade' => 'Mirinzal', 'estado_id' => 10],
            ['cidade' => 'Monção', 'estado_id' => 10],
            ['cidade' => 'Montes Altos', 'estado_id' => 10],
            ['cidade' => 'Morros', 'estado_id' => 10],
            ['cidade' => 'Nina Rodrigues', 'estado_id' => 10],
            ['cidade' => 'Nova Colinas', 'estado_id' => 10],
            ['cidade' => 'Nova Iorque', 'estado_id' => 10],
            ['cidade' => 'Nova Olinda do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Olho d`Água das Cunhãs', 'estado_id' => 10],
            ['cidade' => 'Olinda Nova do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Paço do Lumiar', 'estado_id' => 10],
            ['cidade' => 'Palmeirândia', 'estado_id' => 10],
            ['cidade' => 'Paraibano', 'estado_id' => 10],
            ['cidade' => 'Parnarama', 'estado_id' => 10],
            ['cidade' => 'Passagem Franca', 'estado_id' => 10],
            ['cidade' => 'Pastos Bons', 'estado_id' => 10],
            ['cidade' => 'Paulino Neves', 'estado_id' => 10],
            ['cidade' => 'Paulo Ramos', 'estado_id' => 10],
            ['cidade' => 'Pedreiras', 'estado_id' => 10],
            ['cidade' => 'Pedro do Rosário', 'estado_id' => 10],
            ['cidade' => 'Penalva', 'estado_id' => 10],
            ['cidade' => 'Peri Mirim', 'estado_id' => 10],
            ['cidade' => 'Peritoró', 'estado_id' => 10],
            ['cidade' => 'Pindaré-Mirim', 'estado_id' => 10],
            ['cidade' => 'Pinheiro', 'estado_id' => 10],
            ['cidade' => 'Pio XII', 'estado_id' => 10],
            ['cidade' => 'Pirapemas', 'estado_id' => 10],
            ['cidade' => 'Poção de Pedras', 'estado_id' => 10],
            ['cidade' => 'Porto Franco', 'estado_id' => 10],
            ['cidade' => 'Porto Rico do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Presidente Dutra', 'estado_id' => 10],
            ['cidade' => 'Presidente Juscelino', 'estado_id' => 10],
            ['cidade' => 'Presidente Médici', 'estado_id' => 10],
            ['cidade' => 'Presidente Sarney', 'estado_id' => 10],
            ['cidade' => 'Presidente Vargas', 'estado_id' => 10],
            ['cidade' => 'Primeira Cruz', 'estado_id' => 10],
            ['cidade' => 'Raposa', 'estado_id' => 10],
            ['cidade' => 'Riachão', 'estado_id' => 10],
            ['cidade' => 'Ribamar Fiquene', 'estado_id' => 10],
            ['cidade' => 'Rosário', 'estado_id' => 10],
            ['cidade' => 'Sambaíba', 'estado_id' => 10],
            ['cidade' => 'Santa Filomena do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Santa Helena', 'estado_id' => 10],
            ['cidade' => 'Santa Inês', 'estado_id' => 10],
            ['cidade' => 'Santa Luzia', 'estado_id' => 10],
            ['cidade' => 'Santa Luzia do Paruá', 'estado_id' => 10],
            ['cidade' => 'Santa Quitéria do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Santa Rita', 'estado_id' => 10],
            ['cidade' => 'Santana do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Santo Amaro do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Santo Antônio dos Lopes', 'estado_id' => 10],
            ['cidade' => 'São Benedito do Rio Preto', 'estado_id' => 10],
            ['cidade' => 'São Bento', 'estado_id' => 10],
            ['cidade' => 'São Bernardo', 'estado_id' => 10],
            ['cidade' => 'São Domingos do Azeitão', 'estado_id' => 10],
            ['cidade' => 'São Domingos do Maranhão', 'estado_id' => 10],
            ['cidade' => 'São Félix de Balsas', 'estado_id' => 10],
            ['cidade' => 'São Francisco do Brejão', 'estado_id' => 10],
            ['cidade' => 'São Francisco do Maranhão', 'estado_id' => 10],
            ['cidade' => 'São João Batista', 'estado_id' => 10],
            ['cidade' => 'São João do Carú', 'estado_id' => 10],
            ['cidade' => 'São João do Paraíso', 'estado_id' => 10],
            ['cidade' => 'São João do Soter', 'estado_id' => 10],
            ['cidade' => 'São João dos Patos', 'estado_id' => 10],
            ['cidade' => 'São José de Ribamar', 'estado_id' => 10],
            ['cidade' => 'São José dos Basílios', 'estado_id' => 10],
            ['cidade' => 'São Luís', 'estado_id' => 10],
            ['cidade' => 'São Luís Gonzaga do Maranhão', 'estado_id' => 10],
            ['cidade' => 'São Mateus do Maranhão', 'estado_id' => 10],
            ['cidade' => 'São Pedro da Água Branca', 'estado_id' => 10],
            ['cidade' => 'São Pedro dos Crentes', 'estado_id' => 10],
            ['cidade' => 'São Raimundo das Mangabeiras', 'estado_id' => 10],
            ['cidade' => 'São Raimundo do Doca Bezerra', 'estado_id' => 10],
            ['cidade' => 'São Roberto', 'estado_id' => 10],
            ['cidade' => 'São Vicente Ferrer', 'estado_id' => 10],
            ['cidade' => 'Satubinha', 'estado_id' => 10],
            ['cidade' => 'Senador Alexandre Costa', 'estado_id' => 10],
            ['cidade' => 'Senador La Rocque', 'estado_id' => 10],
            ['cidade' => 'Serrano do Maranhão', 'estado_id' => 10],
            ['cidade' => 'Sítio Novo', 'estado_id' => 10],
            ['cidade' => 'Sucupira do Norte', 'estado_id' => 10],
            ['cidade' => 'Sucupira do Riachão', 'estado_id' => 10],
            ['cidade' => 'Tasso Fragoso', 'estado_id' => 10],
            ['cidade' => 'Timbiras', 'estado_id' => 10],
            ['cidade' => 'Timon', 'estado_id' => 10],
            ['cidade' => 'Trizidela do Vale', 'estado_id' => 10],
            ['cidade' => 'Tufilândia', 'estado_id' => 10],
            ['cidade' => 'Tuntum', 'estado_id' => 10],
            ['cidade' => 'Turiaçu', 'estado_id' => 10],
            ['cidade' => 'Turilândia', 'estado_id' => 10],
            ['cidade' => 'Tutóia', 'estado_id' => 10],
            ['cidade' => 'Urbano Santos', 'estado_id' => 10],
            ['cidade' => 'Vargem Grande', 'estado_id' => 10],
            ['cidade' => 'Viana', 'estado_id' => 10],
            ['cidade' => 'Vila Nova dos Martírios', 'estado_id' => 10],
            ['cidade' => 'Vitória do Mearim', 'estado_id' => 10],
            ['cidade' => 'Vitorino Freire', 'estado_id' => 10],
            ['cidade' => 'Zé Doca', 'estado_id' => 10]
        ]);

        $this->command->info('Cidades do Maranhão importadas com sucesso!');
    }
}