<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesBahiaSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['cidade' => 'Abaíra', 'estado_id' => 5],
            ['cidade' => 'Abaré', 'estado_id' => 5],
            ['cidade' => 'Acajutiba', 'estado_id' => 5],
            ['cidade' => 'Adustina', 'estado_id' => 5],
            ['cidade' => 'Água Fria', 'estado_id' => 5],
            ['cidade' => 'Aiquara', 'estado_id' => 5],
            ['cidade' => 'Alagoinhas', 'estado_id' => 5],
            ['cidade' => 'Alcobaça', 'estado_id' => 5],
            ['cidade' => 'Almadina', 'estado_id' => 5],
            ['cidade' => 'Amargosa', 'estado_id' => 5],
            ['cidade' => 'Amélia Rodrigues', 'estado_id' => 5],
            ['cidade' => 'América Dourada', 'estado_id' => 5],
            ['cidade' => 'Anagé', 'estado_id' => 5],
            ['cidade' => 'Andaraí', 'estado_id' => 5],
            ['cidade' => 'Andorinha', 'estado_id' => 5],
            ['cidade' => 'Angical', 'estado_id' => 5],
            ['cidade' => 'Anguera', 'estado_id' => 5],
            ['cidade' => 'Antas', 'estado_id' => 5],
            ['cidade' => 'Antônio Cardoso', 'estado_id' => 5],
            ['cidade' => 'Antônio Gonçalves', 'estado_id' => 5],
            ['cidade' => 'Aporá', 'estado_id' => 5],
            ['cidade' => 'Apuarema', 'estado_id' => 5],
            ['cidade' => 'Araças', 'estado_id' => 5],
            ['cidade' => 'Aracatu', 'estado_id' => 5],
            ['cidade' => 'Araci', 'estado_id' => 5],
            ['cidade' => 'Aramari', 'estado_id' => 5],
            ['cidade' => 'Arataca', 'estado_id' => 5],
            ['cidade' => 'Aratuípe', 'estado_id' => 5],
            ['cidade' => 'Aurelino Leal', 'estado_id' => 5],
            ['cidade' => 'Baianópolis', 'estado_id' => 5],
            ['cidade' => 'Baixa Grande', 'estado_id' => 5],
            ['cidade' => 'Banzaê', 'estado_id' => 5],
            ['cidade' => 'Barra', 'estado_id' => 5],
            ['cidade' => 'Barra da Estiva', 'estado_id' => 5],
            ['cidade' => 'Barra do Choça', 'estado_id' => 5],
            ['cidade' => 'Barra do Mendes', 'estado_id' => 5],
            ['cidade' => 'Barra do Rocha', 'estado_id' => 5],
            ['cidade' => 'Barreiras', 'estado_id' => 5],
            ['cidade' => 'Barro Alto', 'estado_id' => 5],
            ['cidade' => 'Barro Preto [igo Gov. Lomanto Jr.)', 'estado_id' => 5],
            ['cidade' => 'Barrocas', 'estado_id' => 5],
            ['cidade' => 'Belmonte', 'estado_id' => 5],
            ['cidade' => 'Belo Campo', 'estado_id' => 5],
            ['cidade' => 'Biritinga', 'estado_id' => 5],
            ['cidade' => 'Boa Nova', 'estado_id' => 5],
            ['cidade' => 'Boa Vista do Tupim', 'estado_id' => 5],
            ['cidade' => 'Bom Jesus da Lapa', 'estado_id' => 5],
            ['cidade' => 'Bom Jesus da Serra', 'estado_id' => 5],
            ['cidade' => 'Boninal', 'estado_id' => 5],
            ['cidade' => 'Bonito', 'estado_id' => 5],
            ['cidade' => 'Boquira', 'estado_id' => 5],
            ['cidade' => 'Botuporã', 'estado_id' => 5],
            ['cidade' => 'Brejões', 'estado_id' => 5],
            ['cidade' => 'Brejolândia', 'estado_id' => 5],
            ['cidade' => 'Brotas de Macaúbas', 'estado_id' => 5],
            ['cidade' => 'Brumado', 'estado_id' => 5],
            ['cidade' => 'Buerarema', 'estado_id' => 5],
            ['cidade' => 'Buritirama', 'estado_id' => 5],
            ['cidade' => 'Caatiba', 'estado_id' => 5],
            ['cidade' => 'Cabaceiras do Paraguaçu', 'estado_id' => 5],
            ['cidade' => 'Cachoeira', 'estado_id' => 5],
            ['cidade' => 'Caculé', 'estado_id' => 5],
            ['cidade' => 'Caém', 'estado_id' => 5],
            ['cidade' => 'Caetanos', 'estado_id' => 5],
            ['cidade' => 'Caetité', 'estado_id' => 5],
            ['cidade' => 'Cafarnaum', 'estado_id' => 5],
            ['cidade' => 'Cairu', 'estado_id' => 5],
            ['cidade' => 'Caldeirão Grande', 'estado_id' => 5],
            ['cidade' => 'Camacan', 'estado_id' => 5],
            ['cidade' => 'Camaçari', 'estado_id' => 5],
            ['cidade' => 'Camamu', 'estado_id' => 5],
            ['cidade' => 'Campo Alegre de Lourdes', 'estado_id' => 5],
            ['cidade' => 'Campo Formoso', 'estado_id' => 5],
            ['cidade' => 'Canápolis', 'estado_id' => 5],
            ['cidade' => 'Canarana', 'estado_id' => 5],
            ['cidade' => 'Canavieiras', 'estado_id' => 5],
            ['cidade' => 'Candeal', 'estado_id' => 5],
            ['cidade' => 'Candeias', 'estado_id' => 5],
            ['cidade' => 'Candiba', 'estado_id' => 5],
            ['cidade' => 'Cândido Sales', 'estado_id' => 5],
            ['cidade' => 'Cansanção', 'estado_id' => 5],
            ['cidade' => 'Canudos', 'estado_id' => 5],
            ['cidade' => 'Capela do Alto Alegre', 'estado_id' => 5],
            ['cidade' => 'Capim Grosso', 'estado_id' => 5],
            ['cidade' => 'Caraíbas', 'estado_id' => 5],
            ['cidade' => 'Caravelas', 'estado_id' => 5],
            ['cidade' => 'Cardeal da Silva', 'estado_id' => 5],
            ['cidade' => 'Carinhanha', 'estado_id' => 5],
            ['cidade' => 'Casa Nova', 'estado_id' => 5],
            ['cidade' => 'Castro Alves', 'estado_id' => 5],
            ['cidade' => 'Catolândia', 'estado_id' => 5],
            ['cidade' => 'Catu', 'estado_id' => 5],
            ['cidade' => 'Caturama', 'estado_id' => 5],
            ['cidade' => 'Central', 'estado_id' => 5],
            ['cidade' => 'Chorrochó', 'estado_id' => 5],
            ['cidade' => 'Cícero Dantas', 'estado_id' => 5],
            ['cidade' => 'Cipó', 'estado_id' => 5],
            ['cidade' => 'Coaraci', 'estado_id' => 5],
            ['cidade' => 'Cocos', 'estado_id' => 5],
            ['cidade' => 'Conceição da Feira', 'estado_id' => 5],
            ['cidade' => 'Conceição do Almeida', 'estado_id' => 5],
            ['cidade' => 'Conceição do Coité', 'estado_id' => 5],
            ['cidade' => 'Conceição do Jacuípe', 'estado_id' => 5],
            ['cidade' => 'Conde', 'estado_id' => 5],
            ['cidade' => 'Condeúba', 'estado_id' => 5],
            ['cidade' => 'Contendas do Sincorá', 'estado_id' => 5],
            ['cidade' => 'Coração de Maria', 'estado_id' => 5],
            ['cidade' => 'Cordeiros', 'estado_id' => 5],
            ['cidade' => 'Coribe', 'estado_id' => 5],
            ['cidade' => 'Coronel João Sá', 'estado_id' => 5],
            ['cidade' => 'Correntina', 'estado_id' => 5],
            ['cidade' => 'Cotegipe', 'estado_id' => 5],
            ['cidade' => 'Cravolândia', 'estado_id' => 5],
            ['cidade' => 'Crisópolis', 'estado_id' => 5],
            ['cidade' => 'Cristópolis', 'estado_id' => 5],
            ['cidade' => 'Cruz das Almas', 'estado_id' => 5],
            ['cidade' => 'Curaçá', 'estado_id' => 5],
            ['cidade' => 'Dário Meira', 'estado_id' => 5],
            ['cidade' => 'Dias d`Ávila', 'estado_id' => 5],
            ['cidade' => 'Dom Basílio', 'estado_id' => 5],
            ['cidade' => 'Dom Macedo Costa', 'estado_id' => 5],
            ['cidade' => 'Elísio Medrado', 'estado_id' => 5],
            ['cidade' => 'Encruzilhada', 'estado_id' => 5],
            ['cidade' => 'Entre Rios', 'estado_id' => 5],
            ['cidade' => 'Érico Cardoso', 'estado_id' => 5],
            ['cidade' => 'Esplanada', 'estado_id' => 5],
            ['cidade' => 'Euclides da Cunha', 'estado_id' => 5],
            ['cidade' => 'Eunápolis', 'estado_id' => 5],
            ['cidade' => 'Fátima', 'estado_id' => 5],
            ['cidade' => 'Feira da Mata', 'estado_id' => 5],
            ['cidade' => 'Feira de Santana', 'estado_id' => 5],
            ['cidade' => 'Filadélfia', 'estado_id' => 5],
            ['cidade' => 'Firmino Alves', 'estado_id' => 5],
            ['cidade' => 'Floresta Azul', 'estado_id' => 5],
            ['cidade' => 'Formosa do Rio Preto', 'estado_id' => 5],
            ['cidade' => 'Gandu', 'estado_id' => 5],
            ['cidade' => 'Gavião', 'estado_id' => 5],
            ['cidade' => 'Gentio do Ouro', 'estado_id' => 5],
            ['cidade' => 'Glória', 'estado_id' => 5],
            ['cidade' => 'Gongogi', 'estado_id' => 5],
            ['cidade' => 'Governador Mangabeira', 'estado_id' => 5],
            ['cidade' => 'Guajeru', 'estado_id' => 5],
            ['cidade' => 'Guanambi', 'estado_id' => 5],
            ['cidade' => 'Guaratinga', 'estado_id' => 5],
            ['cidade' => 'Heliópolis', 'estado_id' => 5],
            ['cidade' => 'Iaçu', 'estado_id' => 5],
            ['cidade' => 'Ibiassucê', 'estado_id' => 5],
            ['cidade' => 'Ibicaraí', 'estado_id' => 5],
            ['cidade' => 'Ibicoara', 'estado_id' => 5],
            ['cidade' => 'Ibicuí', 'estado_id' => 5],
            ['cidade' => 'Ibipeba', 'estado_id' => 5],
            ['cidade' => 'Ibipitanga', 'estado_id' => 5],
            ['cidade' => 'Ibiquera', 'estado_id' => 5],
            ['cidade' => 'Ibirapitanga', 'estado_id' => 5],
            ['cidade' => 'Ibirapuã', 'estado_id' => 5],
            ['cidade' => 'Ibirataia', 'estado_id' => 5],
            ['cidade' => 'Ibitiara', 'estado_id' => 5],
            ['cidade' => 'Ibititá', 'estado_id' => 5],
            ['cidade' => 'Ibotirama', 'estado_id' => 5],
            ['cidade' => 'Ichu', 'estado_id' => 5],
            ['cidade' => 'Igaporã', 'estado_id' => 5],
            ['cidade' => 'Igrapiúna', 'estado_id' => 5],
            ['cidade' => 'Iguaí', 'estado_id' => 5],
            ['cidade' => 'Ilhéus', 'estado_id' => 5],
            ['cidade' => 'Inhambupe', 'estado_id' => 5],
            ['cidade' => 'Ipecaetá', 'estado_id' => 5],
            ['cidade' => 'Ipiaú', 'estado_id' => 5],
            ['cidade' => 'Ipirá', 'estado_id' => 5],
            ['cidade' => 'Ipupiara', 'estado_id' => 5],
            ['cidade' => 'Irajuba', 'estado_id' => 5],
            ['cidade' => 'Iramaia', 'estado_id' => 5],
            ['cidade' => 'Iraquara', 'estado_id' => 5],
            ['cidade' => 'Irará', 'estado_id' => 5],
            ['cidade' => 'Irecê', 'estado_id' => 5],
            ['cidade' => 'Itabela', 'estado_id' => 5],
            ['cidade' => 'Itaberaba', 'estado_id' => 5],
            ['cidade' => 'Itabuna', 'estado_id' => 5],
            ['cidade' => 'Itacaré', 'estado_id' => 5],
            ['cidade' => 'Itaeté', 'estado_id' => 5],
            ['cidade' => 'Itagi', 'estado_id' => 5],
            ['cidade' => 'Itagibá', 'estado_id' => 5],
            ['cidade' => 'Itagimirim', 'estado_id' => 5],
            ['cidade' => 'Itaguaçu da Bahia', 'estado_id' => 5],
            ['cidade' => 'Itaju do Colônia', 'estado_id' => 5],
            ['cidade' => 'Itajuípe', 'estado_id' => 5],
            ['cidade' => 'Itamaraju', 'estado_id' => 5],
            ['cidade' => 'Itamari', 'estado_id' => 5],
            ['cidade' => 'Itambé', 'estado_id' => 5],
            ['cidade' => 'Itanagra', 'estado_id' => 5],
            ['cidade' => 'Itanhém', 'estado_id' => 5],
            ['cidade' => 'Itaparica', 'estado_id' => 5],
            ['cidade' => 'Itapé', 'estado_id' => 5],
            ['cidade' => 'Itapebi', 'estado_id' => 5],
            ['cidade' => 'Itapetinga', 'estado_id' => 5],
            ['cidade' => 'Itapicuru', 'estado_id' => 5],
            ['cidade' => 'Itapitanga', 'estado_id' => 5],
            ['cidade' => 'Itaquara', 'estado_id' => 5],
            ['cidade' => 'Itarantim', 'estado_id' => 5],
            ['cidade' => 'Itatim', 'estado_id' => 5],
            ['cidade' => 'Itiruçu', 'estado_id' => 5],
            ['cidade' => 'Itiúba', 'estado_id' => 5],
            ['cidade' => 'Itororó', 'estado_id' => 5],
            ['cidade' => 'Ituaçu', 'estado_id' => 5],
            ['cidade' => 'Ituberá', 'estado_id' => 5],
            ['cidade' => 'Iuiú', 'estado_id' => 5],
            ['cidade' => 'Jaborandi', 'estado_id' => 5],
            ['cidade' => 'Jacaraci', 'estado_id' => 5],
            ['cidade' => 'Jacobina', 'estado_id' => 5],
            ['cidade' => 'Jaguaquara', 'estado_id' => 5],
            ['cidade' => 'Jaguarari', 'estado_id' => 5],
            ['cidade' => 'Jaguaripe', 'estado_id' => 5],
            ['cidade' => 'Jandaíra', 'estado_id' => 5],
            ['cidade' => 'Jequié', 'estado_id' => 5],
            ['cidade' => 'Jeremoabo', 'estado_id' => 5],
            ['cidade' => 'Jiquiriçá', 'estado_id' => 5],
            ['cidade' => 'Jitaúna', 'estado_id' => 5],
            ['cidade' => 'João Dourado', 'estado_id' => 5],
            ['cidade' => 'Juazeiro', 'estado_id' => 5],
            ['cidade' => 'Jucuruçu', 'estado_id' => 5],
            ['cidade' => 'Jussara', 'estado_id' => 5],
            ['cidade' => 'Jussari', 'estado_id' => 5],
            ['cidade' => 'Jussiape', 'estado_id' => 5],
            ['cidade' => 'Lafaiete Coutinho', 'estado_id' => 5],
            ['cidade' => 'Lagoa Real', 'estado_id' => 5],
            ['cidade' => 'Laje', 'estado_id' => 5],
            ['cidade' => 'Lajedão', 'estado_id' => 5],
            ['cidade' => 'Lajedinho', 'estado_id' => 5],
            ['cidade' => 'Lajedo do Tabocal', 'estado_id' => 5],
            ['cidade' => 'Lamarão', 'estado_id' => 5],
            ['cidade' => 'Lapão', 'estado_id' => 5],
            ['cidade' => 'Lauro de Freitas', 'estado_id' => 5],
            ['cidade' => 'Lençóis', 'estado_id' => 5],
            ['cidade' => 'Licínio de Almeida', 'estado_id' => 5],
            ['cidade' => 'Livramento de Nossa Senhora', 'estado_id' => 5],
            ['cidade' => 'Luís Eduardo Magalhães', 'estado_id' => 5],
            ['cidade' => 'Macajuba', 'estado_id' => 5],
            ['cidade' => 'Macarani', 'estado_id' => 5],
            ['cidade' => 'Macaúbas', 'estado_id' => 5],
            ['cidade' => 'Macururé', 'estado_id' => 5],
            ['cidade' => 'Madre de Deus', 'estado_id' => 5],
            ['cidade' => 'Maetinga', 'estado_id' => 5],
            ['cidade' => 'Maiquinique', 'estado_id' => 5],
            ['cidade' => 'Mairi', 'estado_id' => 5],
            ['cidade' => 'Malhada', 'estado_id' => 5],
            ['cidade' => 'Malhada de Pedras', 'estado_id' => 5],
            ['cidade' => 'Manoel Vitorino', 'estado_id' => 5],
            ['cidade' => 'Mansidão', 'estado_id' => 5],
            ['cidade' => 'Maracás', 'estado_id' => 5],
            ['cidade' => 'Maragogipe', 'estado_id' => 5],
            ['cidade' => 'Maraú', 'estado_id' => 5],
            ['cidade' => 'Marcionílio Souza', 'estado_id' => 5],
            ['cidade' => 'Mascote', 'estado_id' => 5],
            ['cidade' => 'Mata de São João', 'estado_id' => 5],
            ['cidade' => 'Matina', 'estado_id' => 5],
            ['cidade' => 'Medeiros Neto', 'estado_id' => 5],
            ['cidade' => 'Miguel Calmon', 'estado_id' => 5],
            ['cidade' => 'Milagres', 'estado_id' => 5],
            ['cidade' => 'Mirangaba', 'estado_id' => 5],
            ['cidade' => 'Mirante', 'estado_id' => 5],
            ['cidade' => 'Monte Santo', 'estado_id' => 5],
            ['cidade' => 'Morpará', 'estado_id' => 5],
            ['cidade' => 'Morro do Chapéu', 'estado_id' => 5],
            ['cidade' => 'Mortugaba', 'estado_id' => 5],
            ['cidade' => 'Mucugê', 'estado_id' => 5],
            ['cidade' => 'Mucuri', 'estado_id' => 5],
            ['cidade' => 'Mulungu do Morro', 'estado_id' => 5],
            ['cidade' => 'Mundo Novo', 'estado_id' => 5],
            ['cidade' => 'Muniz Ferreira', 'estado_id' => 5],
            ['cidade' => 'Muquém de São Francisco', 'estado_id' => 5],
            ['cidade' => 'Muritiba', 'estado_id' => 5],
            ['cidade' => 'Mutuípe', 'estado_id' => 5],
            ['cidade' => 'Nazaré', 'estado_id' => 5],
            ['cidade' => 'Nilo Peçanha', 'estado_id' => 5],
            ['cidade' => 'Nordestina', 'estado_id' => 5],
            ['cidade' => 'Nova Canaã', 'estado_id' => 5],
            ['cidade' => 'Nova Fátima', 'estado_id' => 5],
            ['cidade' => 'Nova Ibiá', 'estado_id' => 5],
            ['cidade' => 'Nova Itarana', 'estado_id' => 5],
            ['cidade' => 'Nova Redenção', 'estado_id' => 5],
            ['cidade' => 'Nova Soure', 'estado_id' => 5],
            ['cidade' => 'Nova Viçosa', 'estado_id' => 5],
            ['cidade' => 'Novo Horizonte', 'estado_id' => 5],
            ['cidade' => 'Novo Triunfo', 'estado_id' => 5],
            ['cidade' => 'Olindina', 'estado_id' => 5],
            ['cidade' => 'Oliveira dos Brejinhos', 'estado_id' => 5],
            ['cidade' => 'Ouriçangas', 'estado_id' => 5],
            ['cidade' => 'Ourolândia', 'estado_id' => 5],
            ['cidade' => 'Palmas de Monte Alto', 'estado_id' => 5],
            ['cidade' => 'Palmeiras', 'estado_id' => 5],
            ['cidade' => 'Paramirim', 'estado_id' => 5],
            ['cidade' => 'Paratinga', 'estado_id' => 5],
            ['cidade' => 'Paripiranga', 'estado_id' => 5],
            ['cidade' => 'Pau Brasil', 'estado_id' => 5],
            ['cidade' => 'Paulo Afonso', 'estado_id' => 5],
            ['cidade' => 'Pé de Serra', 'estado_id' => 5],
            ['cidade' => 'Pedrão', 'estado_id' => 5],
            ['cidade' => 'Pedro Alexandre', 'estado_id' => 5],
            ['cidade' => 'Piatã', 'estado_id' => 5],
            ['cidade' => 'Pilão Arcado', 'estado_id' => 5],
            ['cidade' => 'Pindaí', 'estado_id' => 5],
            ['cidade' => 'Pindobaçu', 'estado_id' => 5],
            ['cidade' => 'Pintadas', 'estado_id' => 5],
            ['cidade' => 'Piraí do Norte', 'estado_id' => 5],
            ['cidade' => 'Piripá', 'estado_id' => 5],
            ['cidade' => 'Piritiba', 'estado_id' => 5],
            ['cidade' => 'Planaltino', 'estado_id' => 5],
            ['cidade' => 'Planalto', 'estado_id' => 5],
            ['cidade' => 'Poções', 'estado_id' => 5],
            ['cidade' => 'Pojuca', 'estado_id' => 5],
            ['cidade' => 'Ponto Novo', 'estado_id' => 5],
            ['cidade' => 'Porto Seguro', 'estado_id' => 5],
            ['cidade' => 'Potiraguá', 'estado_id' => 5],
            ['cidade' => 'Prado', 'estado_id' => 5],
            ['cidade' => 'Presidente Dutra', 'estado_id' => 5],
            ['cidade' => 'Presidente Jânio Quadros', 'estado_id' => 5],
            ['cidade' => 'Presidente Tancredo Neves', 'estado_id' => 5],
            ['cidade' => 'Queimadas', 'estado_id' => 5],
            ['cidade' => 'Quijingue', 'estado_id' => 5],
            ['cidade' => 'Quixabeira', 'estado_id' => 5],
            ['cidade' => 'Rafael Jambeiro', 'estado_id' => 5],
            ['cidade' => 'Remanso', 'estado_id' => 5],
            ['cidade' => 'Retirolândia', 'estado_id' => 5],
            ['cidade' => 'Riachão das Neves', 'estado_id' => 5],
            ['cidade' => 'Riachão do Jacuípe', 'estado_id' => 5],
            ['cidade' => 'Riacho de Santana', 'estado_id' => 5],
            ['cidade' => 'Ribeira do Amparo', 'estado_id' => 5],
            ['cidade' => 'Ribeira do Pombal', 'estado_id' => 5],
            ['cidade' => 'Ribeirão do Largo', 'estado_id' => 5],
            ['cidade' => 'Rio de Contas', 'estado_id' => 5],
            ['cidade' => 'Rio do Antônio', 'estado_id' => 5],
            ['cidade' => 'Rio do Pires', 'estado_id' => 5],
            ['cidade' => 'Rio Real', 'estado_id' => 5],
            ['cidade' => 'Rodelas', 'estado_id' => 5],
            ['cidade' => 'Ruy Barbosa', 'estado_id' => 5],
            ['cidade' => 'Salinas da Margarida', 'estado_id' => 5],
            ['cidade' => 'Salvador', 'estado_id' => 5],
            ['cidade' => 'Santa Bárbara', 'estado_id' => 5],
            ['cidade' => 'Santa Brígida', 'estado_id' => 5],
            ['cidade' => 'Santa Cruz Cabrália', 'estado_id' => 5],
            ['cidade' => 'Santa Cruz da Vitória', 'estado_id' => 5],
            ['cidade' => 'Santa Inês', 'estado_id' => 5],
            ['cidade' => 'Santa Luzia', 'estado_id' => 5],
            ['cidade' => 'Santa Maria da Vitória', 'estado_id' => 5],
            ['cidade' => 'Santa Rita de Cássia', 'estado_id' => 5],
            ['cidade' => 'Santa Teresinha', 'estado_id' => 5],
            ['cidade' => 'Santaluz', 'estado_id' => 5],
            ['cidade' => 'Santana', 'estado_id' => 5],
            ['cidade' => 'Santanópolis', 'estado_id' => 5],
            ['cidade' => 'Santo Amaro', 'estado_id' => 5],
            ['cidade' => 'Santo Antônio de Jesus', 'estado_id' => 5],
            ['cidade' => 'Santo Estêvão', 'estado_id' => 5],
            ['cidade' => 'São Desidério', 'estado_id' => 5],
            ['cidade' => 'São Domingos', 'estado_id' => 5],
            ['cidade' => 'São Felipe', 'estado_id' => 5],
            ['cidade' => 'São Félix', 'estado_id' => 5],
            ['cidade' => 'São Félix do Coribe', 'estado_id' => 5],
            ['cidade' => 'São Francisco do Conde', 'estado_id' => 5],
            ['cidade' => 'São Gabriel', 'estado_id' => 5],
            ['cidade' => 'São Gonçalo dos Campos', 'estado_id' => 5],
            ['cidade' => 'São José da Vitória', 'estado_id' => 5],
            ['cidade' => 'São José do Jacuípe', 'estado_id' => 5],
            ['cidade' => 'São Miguel das Matas', 'estado_id' => 5],
            ['cidade' => 'São Sebastião do Passé', 'estado_id' => 5],
            ['cidade' => 'Sapeaçu', 'estado_id' => 5],
            ['cidade' => 'Sátiro Dias', 'estado_id' => 5],
            ['cidade' => 'Saubara', 'estado_id' => 5],
            ['cidade' => 'Saúde', 'estado_id' => 5],
            ['cidade' => 'Seabra', 'estado_id' => 5],
            ['cidade' => 'Sebastião Laranjeiras', 'estado_id' => 5],
            ['cidade' => 'Senhor do Bonfim', 'estado_id' => 5],
            ['cidade' => 'Sento Sé', 'estado_id' => 5],
            ['cidade' => 'Serra do Ramalho', 'estado_id' => 5],
            ['cidade' => 'Serra Dourada', 'estado_id' => 5],
            ['cidade' => 'Serra Preta', 'estado_id' => 5],
            ['cidade' => 'Serrinha', 'estado_id' => 5],
            ['cidade' => 'Serrolândia', 'estado_id' => 5],
            ['cidade' => 'Simões Filho', 'estado_id' => 5],
            ['cidade' => 'Sítio do Mato', 'estado_id' => 5],
            ['cidade' => 'Sítio do Quinto', 'estado_id' => 5],
            ['cidade' => 'Sobradinho', 'estado_id' => 5],
            ['cidade' => 'Souto Soares', 'estado_id' => 5],
            ['cidade' => 'Tabocas do Brejo Velho', 'estado_id' => 5],
            ['cidade' => 'Tanhaçu', 'estado_id' => 5],
            ['cidade' => 'Tanque Novo', 'estado_id' => 5],
            ['cidade' => 'Tanquinho', 'estado_id' => 5],
            ['cidade' => 'Taperoá', 'estado_id' => 5],
            ['cidade' => 'Tapiramutá', 'estado_id' => 5],
            ['cidade' => 'Teixeira de Freitas', 'estado_id' => 5],
            ['cidade' => 'Teodoro Sampaio', 'estado_id' => 5],
            ['cidade' => 'Teofilândia', 'estado_id' => 5],
            ['cidade' => 'Teolândia', 'estado_id' => 5],
            ['cidade' => 'Terra Nova', 'estado_id' => 5],
            ['cidade' => 'Tremedal', 'estado_id' => 5],
            ['cidade' => 'Tucano', 'estado_id' => 5],
            ['cidade' => 'Uauá', 'estado_id' => 5],
            ['cidade' => 'Ubaíra', 'estado_id' => 5],
            ['cidade' => 'Ubaitaba', 'estado_id' => 5],
            ['cidade' => 'Ubatã', 'estado_id' => 5],
            ['cidade' => 'Uibaí', 'estado_id' => 5],
            ['cidade' => 'Umburanas', 'estado_id' => 5],
            ['cidade' => 'Una', 'estado_id' => 5],
            ['cidade' => 'Urandi', 'estado_id' => 5],
            ['cidade' => 'Uruçuca', 'estado_id' => 5],
            ['cidade' => 'Utinga', 'estado_id' => 5],
            ['cidade' => 'Valença', 'estado_id' => 5],
            ['cidade' => 'Valente', 'estado_id' => 5],
            ['cidade' => 'Várzea da Roça', 'estado_id' => 5],
            ['cidade' => 'Várzea do Poço', 'estado_id' => 5],
            ['cidade' => 'Várzea Nova', 'estado_id' => 5],
            ['cidade' => 'Varzedo', 'estado_id' => 5],
            ['cidade' => 'Vera Cruz', 'estado_id' => 5],
            ['cidade' => 'Vereda', 'estado_id' => 5],
            ['cidade' => 'Vitória da Conquista', 'estado_id' => 5],
            ['cidade' => 'Wagner', 'estado_id' => 5],
            ['cidade' => 'Wanderley', 'estado_id' => 5],
            ['cidade' => 'Wenceslau Guimarães', 'estado_id' => 5],
            ['cidade' => 'Xique-Xique', 'estado_id' => 5]
        ]);

        $this->command->info('Cidades da Bahia importadas com sucesso!');
    }
}